import 'package:flutter/material.dart';
import 'package:ticash/localization/app_localizations.dart';

extension FlupFlapTranslations on BuildContext {
  String ft(String key, [Map<String, String> values = const {}]) {
    var text =
        flupFlapStrings[appLanguage.code]?[key] ??
        flupFlapStrings['en']?[key] ??
        key;
    for (final entry in values.entries) {
      text = text.replaceAll('{${entry.key}}', entry.value);
    }
    return text;
  }
}

const Map<String, Map<String, String>> flupFlapStrings = {
  "en": {
    "internetBundles": "Internet & bundles",
    "internetBundlesHelp": "Choose a destination and operator to see available plans.",
    "noInternetOperators": "Internet bundles are not available for this destination.",
    "nationalPhoneHelp":
        "Enter your local number. We add the country code automatically.",
    "invalidNationalPhone":
        "Enter a valid phone number for the selected country.",
    "havePromo": "Have a promo code?",
    "promoUnavailable":
        "This code is invalid, expired, or unavailable for your account.",
    "promoSaved": "Code saved: {name}",
    "copyCode": "Copy referral code",
    "copyReferralLink": "Copy referral link",
    "codeCopied": "Referral code copied",
    "shareAction": "Share",
    "guestReferral": "Create an account to get your referral code",
    "shareHelp": "Invite someone using your personal code, link, or QR code.",
    "pendingPayment": "Pending payment",
    "pendingRecoveryHelp":
        "This payment is not resolved yet. Check its status or cancel it before starting another recharge.",
    "cancelPending": "Cancel pending payment & start new recharge",
    "cancelledStartNew": "Payment cancelled. You can start a new recharge.",
    "cancellationUnresolved":
        "This payment cannot be safely cancelled yet. Check its status before starting another recharge.",
    "unconfirmedValue": "Provider has not confirmed the delivered value.",
    "quotedReceiver": "Quoted receiver value",
    "receiverMismatch":
        "Delivered value differs from the quote. Contact support.",
    "Country code": "Country code",
    "No fixed expiry": "No fixed expiry",
    "REFUND_PENDING": "Refund pending",
    "VOID_PENDING": "Void pending",
    "Add recipient": "Add recipient",
    "destination": "Destination",
    "operatorProduct": "Operator & Product",
    "reviewConfirm": "Review & Confirm",
    "recharge": "Recharge",
    "country": "Country",
    "phone": "International phone number",
    "operator": "Operator",
    "product": "Product",
    "continue": "Continue",
    "back": "Back",
    "amount": "Recharge amount",
    "amountInvalid": "Enter a valid amount with up to 2 decimal places.",
    "amountTooLow": "Minimum recharge amount: {minimum}.",
    "amountTooHigh": "Maximum recharge amount: {maximum}.",
    "amountPrecision": "Use at most {precision} decimal places.",
    "amountIncrement": "Use increments of {increment} starting at {minimum}.",
    "fee": "FlupFlap fee",
    "total": "Total",
    "receiver": "Receiver value",
    "pendingValue": "Confirmed after delivery",
    "quoteExpiry": "Quote expires",
    "reviewCheck": "I have checked the number, product and total.",
    "pay": "Continue to payment",
    "testPay": "Continue to test payment",
    "mockPay": "Confirm MOCK test recharge",
    "mockMode": "MOCK test — no real payment or recharge.",
    "sandboxMode": "Stripe sandbox — test payment only.",
    "billing": "Billing country",
    "billingHelp":
        "The payer/card country can differ from the recipient’s country.",
    "accountCountry": "Manage your stored billing country in Account.",
    "recurringTitle": "Automatic recharge",
    "recurringHelp":
        "Choose every 7, 15, or 30 days. FlupFlap charges your saved card automatically and pauses if the price increases or payment needs your attention.",
    "recurringReviewHelp":
        "Optional: choose how often FlupFlap should automatically recharge this same number after this payment succeeds.",
    "recurringOff": "One-time recharge",
    "recurringSetupPending":
        "Automatic recharge was requested with this payment. Setup is being finalized securely.",
    "recurringConsent":
        "Automatically recharge this same number every {days} days using your saved card. The current total is the maximum allowed; if the price increases, automatic recharge pauses for your approval.",
    "recurringConfirm": "Enable automatic recharge",
    "everyDays": "Every {days} days",
    "recurringFrequency": "Frequency",
    "recurringNext": "Next recharge",
    "recurringStatusACTIVE": "Automatic recharge is active.",
    "recurringStatusPAUSED": "Automatic recharge is paused.",
    "recurringStatusCANCELLED": "Automatic recharge is cancelled.",
    "recurringPause": "Pause",
    "recurringResume": "Resume",
    "recurringCancel": "Cancel automatic recharge",
    "recurringEnabled": "Automatic recharge enabled.",
    "recurringPaused": "Automatic recharge paused.",
    "recurringResumed": "Automatic recharge resumed.",
    "recurringCancelled": "Automatic recharge cancelled.",
    "recurringPaymentUnavailable":
        "This card was not saved for automatic recharge. Complete a new card payment first, then enable automatic recharge.",
    "promo": "Promotion code",
    "apply": "Apply",
    "promotionApplied":
        "Promotion recorded. Request a new quote to review eligibility and benefits.",
    "promotion": "Promotion",
    "originalFee": "Original fee",
    "benefit": "Promotion benefit",
    "firstRecharge": "First eligible recharge only.",
    "nickname": "Save recipient as (optional)",
    "saved": "Saved recipients",
    "retry": "Retry",
    "refresh": "Check status",
    "openCheckout": "Open secure Stripe Checkout",
    "retrySame": "Retry the same payment attempt",
    "pendingNotice":
        "Payment is unresolved. Check status before starting another recharge.",
    "history": "History",
    "receipt": "Receipt",
    "another": "Recharge another phone",
    "repeat": "Repeat with a new quote",
    "search": "Search countries",
    "close": "Close",
    "minimum": "Minimum",
    "maximum": "Maximum",
    "AIRTIME": "Airtime",
    "DATA": "Data",
    "BUNDLE": "Bundle",
    "PENDING": "Pending",
    "PROCESSING": "Processing",
    "DELIVERED": "Delivered",
    "FAILED": "Failed",
    "REFUNDED": "Refund confirmed",
    "VOIDED": "Void confirmed",
    "requestFailed":
        "Unable to complete this request. Please retry or check history.",
    "quoteExpired": "Quote expired. Request and review a fresh quote.",
    "catalogChanged":
        "Catalog changed. Reload products and review a fresh quote.",
    "billingRequired": "Select a billing country before payment.",
    "accountRequired": "Sign in or create an account for this feature.",
    "insufficientFunds": "Payment declined: insufficient funds.",
    "paymentDeclined": "Payment declined. Check your payment details.",
    "resumeUnavailable":
        "Return link unavailable. Sign in and check history before another payment.",
    "share": "Share FlupFlap",
    "copy": "Copy link",
    "copied": "Link copied",
    "qr": "Scan to join FlupFlap",
    "referral": "Referral code",
    "shareMessage": "Join FlupFlap with my referral code {code}: {url}",
    "emptyHistory": "No recharges yet.",
    "noProducts": "No supported products available.",
    "unknownState": "Checking status",
    "paymentCancelled": "Payment cancelled.",
    "providerFailed":
        "Recharge could not be delivered. Check refund or void status.",
    "Conditions": "Conditions",
    "Airtime": "Airtime",
    "Promotion": "Promotion",
    "or": "or",
    "Create an account": "Create an account",
    "Create FlupFlap account": "Create FlupFlap account",
    "Edit": "Edit",
    "Number": "Number",
    "Amount": "Amount",
    "Pay": "Pay",
    "View all": "View all",
    "Minutes": "Minutes",
    "SMS": "SMS",
    "Unlimited": "Unlimited",
    "Validity": "Validity",
    "hours": "hours",
    "days": "days",
    "weeks": "weeks",
    "months": "months",
    "years": "years",
    "Sign in to FlupFlap": "Sign in to FlupFlap",
    "Welcome": "Welcome",
    "Sign in to continue.": "Sign in to continue.",
    "Language": "Language",
    "Show": "Show",
    "Hide": "Hide",
    "Password": "Password",
    "Show password": "Show password",
    "Hide password": "Hide password",
    "First name": "First name",
    "Last name": "Last name",
    "Sign in": "Sign in",
    "Create account": "Create account",
    "Continue as guest": "Continue as guest",
    "Sign out": "Sign out",
    "Destination country": "Destination country",
    "FlupFlap": "FlupFlap",
    "Worldwide Mobile Recharge by TiCash-App":
        "Worldwide Mobile Recharge by TiCash-App",
    "Destination": "Destination",
    "Phone number": "Phone number",
    "Operator": "Operator",
    "Product": "Product",
    "Recharge": "Recharge",
    "RECEIPT": "RECEIPT",
    "Reference": "Reference",
    "Status": "Status",
    "Fee": "Fee",
    "Total": "Total",
    "Updated": "Updated",
    "Support": "Support",
    "Privacy": "Privacy",
    "Terms": "Terms",
    "pending": "pending",
    "processing": "processing",
    "delivered": "delivered",
    "failed": "failed",
    "refunded": "refunded",
    "Refresh": "Refresh",
    "Home": "Home",
    "About": "About",
    "Security": "Security",
    "Contact": "Contact",
    "Forgot password?": "Forgot password?",
    "Guest": "Guest",
    "Country": "Country",
    "Recipient": "Recipient",
    "Continue": "Continue",
    "Billing country": "Billing country",
    "Automatic": "Automatic",
    "Cancel": "Cancel",
    "Delete": "Delete",
    "Pending": "Pending",
    "Processing": "Processing",
    "Delivered": "Delivered",
    "Successful": "Successful",
    "Failed": "Failed",
    "Cancelled": "Cancelled",
    "Refunded": "Refunded",
    "Voided": "Voided",
    "Authorized": "Authorized",
    "Activity unavailable": "Activity unavailable",
    "Already have an account? Sign in": "Already have an account? Sign in",
    "Check your connection and try again.":
        "Check your connection and try again.",
    "Choose a new secure password.": "Choose a new secure password.",
    "Enter a name, country and international phone number.":
        "Enter a name, country and international phone number.",
    "FAST • SIMPLE • WORLDWIDE": "FAST • SIMPLE • WORLDWIDE",
    "FlupFlap account": "FlupFlap account",
    "FlupFlap customer": "FlupFlap customer",
    "Guest recharge session": "Guest recharge session",
    "If an account exists, reset instructions have been sent.":
        "If an account exists, reset instructions have been sent.",
    "No recharges yet": "No recharges yet",
    "No saved recipients yet": "No saved recipients yet",
    "Payments and recharge processing use protected server connections.":
        "Payments and recharge processing use protected server connections.",
    "Please wait…": "Please wait…",
    "Profile updated": "Profile updated",
    "Pull down to try again.": "Pull down to try again.",
    "Quick access": "Quick access",
    "Recent activity": "Recent activity",
    "Recharge family and friends with supported mobile operators around the world.":
        "Recharge family and friends with supported mobile operators around the world.",
    "Recharge phones worldwide in a few taps.":
        "Recharge phones worldwide in a few taps.",
    "Recipient name": "Recipient name",
    "Recipients unavailable": "Recipients unavailable",
    "Recipients you save during checkout will appear here for quick access.":
        "Recipients you save during checkout will appear here for quick access.",
    "Reset FlupFlap password": "Reset FlupFlap password",
    "Retry loading countries": "Retry loading countries",
    "Save people you recharge often": "Save people you recharge often",
    "Save profile": "Save profile",
    "Save recipient": "Save recipient",
    "Saving…": "Saving…",
    "Save someone during a recharge for faster sending next time.":
        "Save someone during a recharge for faster sending next time.",
    "Secure recharge": "Secure recharge",
    "See history": "See history",
    "Send a recharge": "Send a recharge",
    "Send airtime": "Send airtime",
    "Sign in to continue to FlupFlap.": "Sign in to continue to FlupFlap.",
    "Start a recharge": "Start a recharge",
    "Start recharge": "Start recharge",
    "This account is separate from your TiCash remittance account.":
        "This account is separate from your TiCash remittance account.",
    "Track recharges": "Track recharges",
    "Unable to complete this request. Check your details and try again.":
        "Unable to complete this request. Check your details and try again.",
    "Unable to load recipients": "Unable to load recipients",
    "Unable to save recipient. Check the details and try again.":
        "Unable to save recipient. Check the details and try again.",
    "Unable to update profile": "Unable to update profile",
    "Update password": "Update password",
    "Use the 2-letter country code for your billing profile.":
        "Use the 2-letter country code for your billing profile.",
    "Worldwide mobile recharge": "Worldwide mobile recharge",
    "Your latest recharge will appear here.":
        "Your latest recharge will appear here.",
    "Your recharge history could not be loaded.":
        "Your recharge history could not be loaded.",
    "Account": "Account",
    "Recipients": "Recipients",
    "Profile": "Profile",
    "Email": "Email",
  },
  "ht": {
    "internetBundles": "Entènèt ak pake",
    "internetBundlesHelp": "Chwazi yon destinasyon ak operatè pou wè pake ki disponib yo.",
    "noInternetOperators": "Pa gen pake entènèt disponib pou destinasyon sa a.",
    "nationalPhoneHelp":
        "Antre nimewo lokal ou. Nou ajoute kòd peyi a otomatikman.",
    "invalidNationalPhone":
        "Antre yon nimewo telefòn ki valab pou peyi ou chwazi a.",
    "havePromo": "Ou gen yon kòd pwomosyon?",
    "promoUnavailable":
        "Kòd sa a pa valab, li ekspire, oswa li pa disponib pou kont ou.",
    "promoSaved": "Kòd anrejistre: {name}",
    "copyCode": "Kopye kòd referans",
    "copyReferralLink": "Kopye lyen referans",
    "codeCopied": "Kòd referans kopye",
    "shareAction": "Pataje",
    "guestReferral": "Kreye yon kont pou jwenn kòd referans ou",
    "shareHelp": "Envite yon moun ak kòd pèsonèl ou, lyen ou oswa kòd QR ou.",
    "pendingPayment": "Peman annatant",
    "pendingRecoveryHelp":
        "Peman sa a poko rezoud. Verifye estati li oswa anile li anvan ou kòmanse yon lòt rechaj.",
    "cancelPending": "Anile peman annatant lan epi kòmanse yon nouvo rechaj",
    "cancelledStartNew": "Peman an anile. Ou ka kòmanse yon nouvo rechaj.",
    "cancellationUnresolved":
        "Peman sa a poko ka anile san danje. Verifye estati li anvan ou kòmanse yon lòt rechaj.",
    "unconfirmedValue": "Founisè a poko konfime valè ki delivre a.",
    "quotedReceiver": "Valè reseptè ki nan devis la",
    "receiverMismatch": "Valè ki delivre a diferan de devis la. Kontakte sipò.",
    "Country code": "Kòd peyi",
    "No fixed expiry": "Pa gen dat ekspirasyon fiks",
    "REFUND_PENDING": "Ranbousman annatant",
    "VOID_PENDING": "Anilasyon annatant",
    "Add recipient": "Ajoute benefisyè",
    "destination": "Destinasyon",
    "operatorProduct": "Operatè ak pwodwi",
    "reviewConfirm": "Revize epi konfime",
    "recharge": "Rechaj",
    "country": "Peyi",
    "phone": "Nimewo telefòn entènasyonal",
    "operator": "Operatè",
    "product": "Pwodwi",
    "continue": "Kontinye",
    "back": "Retounen",
    "amount": "Montan rechaj",
    "amountInvalid": "Antre yon montan valab ak jiska 2 chif apre vigil la.",
    "amountTooLow": "Montan rechaj minimòm: {minimum}.",
    "amountTooHigh": "Montan rechaj maksimòm: {maximum}.",
    "amountPrecision": "Itilize omaksimòm {precision} chif apre vigil la.",
    "amountIncrement": "Itilize pa {increment} apati {minimum}.",
    "fee": "Frè FlupFlap",
    "total": "Total",
    "receiver": "Valè benefisyè a",
    "pendingValue": "Konfime apre livrezon",
    "quoteExpiry": "Pri a ekspire",
    "reviewCheck": "Mwen verifye nimewo a, pwodwi a ak total la.",
    "pay": "Kontinye nan peman",
    "testPay": "Kontinye nan peman tès",
    "mockPay": "Konfime rechaj tès MOCK",
    "mockMode": "Tès MOCK — pa gen peman oswa rechaj reyèl.",
    "sandboxMode": "Stripe sandbox — peman tès sèlman.",
    "billing": "Peyi fakti",
    "billingHelp": "Peyi moun k ap peye a ka diferan ak peyi benefisyè a.",
    "accountCountry": "Jere peyi fakti ki anrejistre a nan Kont.",
    "recurringTitle": "Rechaj otomatik",
    "recurringHelp": "Chwazi chak 7, 15, oswa 30 jou. FlupFlap chaje kat ou anrejistre otomatikman epi li mete sèvis la an poz si pri a ogmante oswa peman an bezwen atansyon ou.",
    "recurringReviewHelp": "Opsyonèl: chwazi konbyen fwa FlupFlap dwe rechaje menm nimewo sa a otomatikman apre peman sa a reyisi.",
    "recurringOff": "Rechaj yon sèl fwa",
    "recurringSetupPending": "Yo mande rechaj otomatik ak peman sa a. N ap finalize konfigirasyon an an sekirite.",
    "recurringConsent": "Rechaje menm nimewo sa a otomatikman chak {days} jou ak kat ou anrejistre. Total aktyèl la se maksimòm ki otorize; si pri a ogmante, rechaj otomatik la ap pran poz pou apwobasyon ou.",
    "recurringConfirm": "Aktive rechaj otomatik",
    "everyDays": "Chak {days} jou",
    "recurringFrequency": "Frekans",
    "recurringNext": "Pwochen rechaj",
    "recurringStatusACTIVE": "Rechaj otomatik aktif.",
    "recurringStatusPAUSED": "Rechaj otomatik an poz.",
    "recurringStatusCANCELLED": "Rechaj otomatik anile.",
    "recurringPause": "Mete an poz",
    "recurringResume": "Reprann",
    "recurringCancel": "Anile rechaj otomatik",
    "recurringEnabled": "Rechaj otomatik aktive.",
    "recurringPaused": "Rechaj otomatik mete an poz.",
    "recurringResumed": "Rechaj otomatik reprann.",
    "recurringCancelled": "Rechaj otomatik anile.",
    "recurringPaymentUnavailable": "Kat sa a pa te anrejistre pou rechaj otomatik. Fè yon nouvo peman ak kat anvan, epi aktive rechaj otomatik.",
    "promo": "Kòd pwomosyon",
    "apply": "Aplike",
    "promotionApplied":
        "Pwomosyon an anrejistre. Mande yon nouvo pri pou revize avantaj yo.",
    "promotion": "Pwomosyon",
    "originalFee": "Frè orijinal",
    "benefit": "Avantaj pwomosyon",
    "firstRecharge": "Premye rechaj elijib sèlman.",
    "nickname": "Sove benefisyè kòm (opsyonèl)",
    "saved": "Benefisyè anrejistre",
    "retry": "Eseye ankò",
    "refresh": "Verifye estati",
    "openCheckout": "Louvri Stripe Checkout an sekirite",
    "retrySame": "Eseye menm tantativ peman an",
    "pendingNotice":
        "Peman an poko rezoud. Verifye estati anvan yon lòt rechaj.",
    "history": "Istwa",
    "receipt": "Resi",
    "another": "Rechaje yon lòt telefòn",
    "repeat": "Repete avèk yon nouvo pri",
    "search": "Chèche peyi",
    "close": "Fèmen",
    "minimum": "Minimòm",
    "maximum": "Maksimòm",
    "AIRTIME": "Kredi telefòn",
    "DATA": "Done",
    "BUNDLE": "Pakè",
    "PENDING": "Annatant",
    "PROCESSING": "An tretman",
    "DELIVERED": "Livre",
    "FAILED": "Echwe",
    "REFUNDED": "Ranbousman konfime",
    "VOIDED": "Anilasyon konfime",
    "requestFailed":
        "Nou pa ka fini demann lan. Eseye ankò oswa verifye istwa.",
    "quoteExpired": "Pri a ekspire. Mande epi revize yon nouvo pri.",
    "catalogChanged":
        "Katalòg la chanje. Rechaje pwodwi yo epi revize yon nouvo pri.",
    "billingRequired": "Chwazi yon peyi fakti anvan peman.",
    "accountRequired": "Konekte oswa kreye yon kont pou fonksyon sa a.",
    "insufficientFunds": "Peman refize: pa gen ase lajan.",
    "paymentDeclined": "Peman refize. Verifye enfòmasyon peman ou.",
    "resumeUnavailable":
        "Lyen retou a pa disponib. Konekte epi verifye istwa anvan yon lòt peman.",
    "share": "Pataje FlupFlap",
    "copy": "Kopye lyen",
    "copied": "Lyen kopye",
    "qr": "Eskane pou rantre nan FlupFlap",
    "referral": "Kòd referans",
    "shareMessage": "Antre nan FlupFlap ak kòd referans mwen {code}: {url}",
    "emptyHistory": "Pa gen rechaj ankò.",
    "noProducts": "Pa gen pwodwi sipòte disponib.",
    "unknownState": "N ap verifye estati",
    "paymentCancelled": "Peman anile.",
    "providerFailed":
        "Rechaj la pa t livre. Verifye estati ranbousman oswa anilasyon.",
    "Conditions": "Kondisyon",
    "Airtime": "Kredi telefòn",
    "Promotion": "Pwomosyon",
    "or": "oswa",
    "Create an account": "Kreye kont",
    "Create FlupFlap account": "Kreye kont FlupFlap",
    "Edit": "Modifye",
    "Number": "Nimewo",
    "Amount": "Montan",
    "Pay": "Peye",
    "View all": "Wè tout",
    "Minutes": "Minit",
    "SMS": "SMS",
    "Unlimited": "San limit",
    "Validity": "Dire validite",
    "hours": "èdtan",
    "days": "jou",
    "weeks": "semèn",
    "months": "mwa",
    "years": "ane",
    "Sign in to FlupFlap": "Konekte nan FlupFlap",
    "Welcome": "Byenveni",
    "Sign in to continue.": "Konekte pou kontinye.",
    "Language": "Lang",
    "Show": "Montre",
    "Hide": "Kache",
    "Password": "Modpas",
    "Show password": "Montre modpas la",
    "Hide password": "Kache modpas la",
    "First name": "Non",
    "Last name": "Siyati",
    "Sign in": "Konekte",
    "Create account": "Kreye kont",
    "Continue as guest": "Kontinye kòm envite",
    "Sign out": "Dekonekte",
    "Destination country": "Peyi destinasyon",
    "FlupFlap": "FlupFlap",
    "Worldwide Mobile Recharge by TiCash-App":
        "Rechaj mobil atravè mond lan pa TiCash-App",
    "Destination": "Destinasyon",
    "Phone number": "Nimewo telefòn",
    "Operator": "Operatè",
    "Product": "Pwodui",
    "Recharge": "Rechaj",
    "RECEIPT": "RESI",
    "Reference": "Referans",
    "Status": "Estati",
    "Fee": "Frè",
    "Total": "Total",
    "Updated": "Mizajou",
    "Support": "Èd",
    "Privacy": "Konfidansyalite",
    "Terms": "Kondisyon",
    "pending": "ann atant",
    "processing": "ap trete",
    "delivered": "livre",
    "failed": "echwe",
    "refunded": "ranbouse",
    "Refresh": "Rafrechi",
    "Home": "Akèy",
    "About": "Konsènan",
    "Security": "Sekirite",
    "Contact": "Kontak",
    "Forgot password?": "Ou bliye modpas ou?",
    "Guest": "Envite",
    "Country": "Peyi",
    "Recipient": "Moun k ap resevwa",
    "Continue": "Kontinye",
    "Billing country": "Peyi pou fakti",
    "Automatic": "Otomatik",
    "Cancel": "Anile",
    "Delete": "Efase",
    "Pending": "Annatant",
    "Processing": "Ap trete",
    "Delivered": "Livre",
    "Successful": "Reyisi",
    "Failed": "Echwe",
    "Cancelled": "Anile",
    "Refunded": "Ranbouse",
    "Voided": "Peman anile",
    "Authorized": "Otorize",
    "Activity unavailable": "Aktivite pa disponib",
    "Already have an account? Sign in": "Ou deja gen yon kont? Konekte",
    "Check your connection and try again.":
        "Verifye koneksyon ou epi eseye ankò.",
    "Choose a new secure password.": "Chwazi yon nouvo modpas an sekirite.",
    "Enter a name, country and international phone number.":
        "Antre yon non, peyi ak nimewo entènasyonal.",
    "FAST • SIMPLE • WORLDWIDE": "RAPID • SENP • ATRAVÈ MOND LAN",
    "FlupFlap account": "Kont FlupFlap",
    "FlupFlap customer": "Kliyan FlupFlap",
    "Guest recharge session": "Sesyon rechaj envite",
    "If an account exists, reset instructions have been sent.":
        "Si kont lan egziste, enstriksyon yo voye.",
    "No recharges yet": "Pa gen rechaj ankò",
    "No saved recipients yet": "Pa gen benefisyè anrejistre",
    "Payments and recharge processing use protected server connections.":
        "Peman ak rechaj sèvi ak koneksyon sèvè pwoteje.",
    "Please wait…": "Tanpri tann…",
    "Profile updated": "Pwofil mete ajou",
    "Pull down to try again.": "Rale desann pou eseye ankò.",
    "Quick access": "Aksè rapid",
    "Recent activity": "Aktivite resan",
    "Recharge family and friends with supported mobile operators around the world.":
        "Rechaje fanmi ak zanmi avèk operatè mobil ki sipòte atravè mond lan.",
    "Recharge phones worldwide in a few taps.":
        "Rechaje telefòn atravè mond lan an kèk klik.",
    "Recipient name": "Non benefisyè",
    "Recipients unavailable": "Benefisyè pa disponib",
    "Recipients you save during checkout will appear here for quick access.":
        "Benefisyè ou sove pandan peman ap parèt isit la.",
    "Reset FlupFlap password": "Reyinisyalize modpas FlupFlap",
    "Retry loading countries": "Eseye chaje peyi yo ankò",
    "Save people you recharge often": "Sove moun ou rechaje souvan",
    "Save profile": "Sove pwofil",
    "Save recipient": "Sove benefisyè",
    "Saving…": "N ap sove…",
    "Save someone during a recharge for faster sending next time.":
        "Sove yon moun pandan rechaj pou pwochen fwa.",
    "Secure recharge": "Rechaj an sekirite",
    "See history": "Gade istwa",
    "Send a recharge": "Voye yon rechaj",
    "Send airtime": "Voye kredi telefòn",
    "Sign in to continue to FlupFlap.": "Konekte pou kontinye nan FlupFlap.",
    "Start a recharge": "Kòmanse yon rechaj",
    "Start recharge": "Kòmanse rechaj",
    "This account is separate from your TiCash remittance account.":
        "Kont sa a separe ak kont transfè TiCash ou.",
    "Track recharges": "Swiv rechaj yo",
    "Unable to complete this request. Check your details and try again.":
        "Nou pa ka fini demann lan. Verifye detay yo epi eseye ankò.",
    "Unable to load recipients": "Nou pa ka chaje benefisyè yo",
    "Unable to save recipient. Check the details and try again.":
        "Nou pa ka sove benefisyè a. Verifye detay yo.",
    "Unable to update profile": "Nou pa ka mete pwofil la ajou",
    "Update password": "Mete modpas ajou",
    "Use the 2-letter country code for your billing profile.":
        "Sèvi ak kòd peyi 2 lèt pou pwofil fakti ou.",
    "Worldwide mobile recharge": "Rechaj mobil atravè mond lan",
    "Your latest recharge will appear here.":
        "Dènye rechaj ou ap parèt isit la.",
    "Your recharge history could not be loaded.":
        "Istwa rechaj ou pa t ka chaje.",
    "Account": "Kont",
    "Recipients": "Benefisyè",
    "Profile": "Pwofil",
    "Email": "Imèl",
  },
  "fr": {
    "internetBundles": "Internet et forfaits",
    "internetBundlesHelp": "Choisissez une destination et un opérateur pour voir les forfaits disponibles.",
    "noInternetOperators": "Aucun forfait internet disponible pour cette destination.",
    "nationalPhoneHelp":
        "Saisissez votre numéro local. Nous ajoutons l’indicatif automatiquement.",
    "invalidNationalPhone":
        "Saisissez un numéro valide pour le pays sélectionné.",
    "havePromo": "Vous avez un code promo ?",
    "promoUnavailable":
        "Ce code est invalide, expiré ou indisponible pour votre compte.",
    "promoSaved": "Code enregistré : {name}",
    "copyCode": "Copier le code de parrainage",
    "copyReferralLink": "Copier le lien de parrainage",
    "codeCopied": "Code de parrainage copié",
    "shareAction": "Partager",
    "guestReferral": "Créez un compte pour obtenir votre code de parrainage",
    "shareHelp":
        "Invitez quelqu’un avec votre code personnel, votre lien ou votre code QR.",
    "pendingPayment": "Paiement en attente",
    "pendingRecoveryHelp":
        "Ce paiement n’est pas encore résolu. Vérifiez son état ou annulez-le avant de commencer une autre recharge.",
    "cancelPending":
        "Annuler le paiement en attente et commencer une nouvelle recharge",
    "cancelledStartNew":
        "Paiement annulé. Vous pouvez commencer une nouvelle recharge.",
    "cancellationUnresolved":
        "Ce paiement ne peut pas encore être annulé en toute sécurité. Vérifiez son état avant de commencer une autre recharge.",
    "unconfirmedValue": "Le fournisseur n’a pas confirmé la valeur livrée.",
    "quotedReceiver": "Valeur prévue pour le bénéficiaire",
    "receiverMismatch":
        "La valeur livrée diffère du devis. Contactez le support.",
    "Country code": "Code pays",
    "No fixed expiry": "Sans expiration fixe",
    "REFUND_PENDING": "Remboursement en attente",
    "VOID_PENDING": "Annulation en attente",
    "Add recipient": "Ajouter un bénéficiaire",
    "destination": "Destination",
    "operatorProduct": "Opérateur et produit",
    "reviewConfirm": "Vérifier et confirmer",
    "recharge": "Recharge",
    "country": "Pays",
    "phone": "Numéro de téléphone international",
    "operator": "Opérateur",
    "product": "Produit",
    "continue": "Continuer",
    "back": "Retour",
    "amount": "Montant de recharge",
    "amountInvalid": "Saisissez un montant valide avec au plus 2 décimales.",
    "amountTooLow": "Montant minimum de recharge : {minimum}.",
    "amountTooHigh": "Montant maximum de recharge : {maximum}.",
    "amountPrecision": "Utilisez au maximum {precision} décimales.",
    "amountIncrement":
        "Utilisez des paliers de {increment} à partir de {minimum}.",
    "fee": "Frais FlupFlap",
    "total": "Total",
    "receiver": "Valeur reçue",
    "pendingValue": "Confirmée après livraison",
    "quoteExpiry": "Expiration du devis",
    "reviewCheck": "J’ai vérifié le numéro, le produit et le total.",
    "pay": "Continuer vers le paiement",
    "testPay": "Continuer vers le paiement test",
    "mockPay": "Confirmer la recharge test MOCK",
    "mockMode": "Test MOCK — aucun paiement ni recharge réels.",
    "sandboxMode": "Stripe sandbox — paiement test uniquement.",
    "billing": "Pays de facturation",
    "billingHelp": "Le pays du payeur peut différer de celui du destinataire.",
    "accountCountry": "Gérez votre pays de facturation dans Compte.",
    "recurringTitle": "Recharge automatique",
    "recurringHelp": "Choisissez tous les 7, 15 ou 30 jours. FlupFlap débite automatiquement votre carte enregistrée et suspend le service si le prix augmente ou si le paiement nécessite votre attention.",
    "recurringReviewHelp": "Facultatif : choisissez la fréquence à laquelle FlupFlap doit recharger automatiquement ce même numéro après la réussite de ce paiement.",
    "recurringOff": "Recharge unique",
    "recurringSetupPending": "La recharge automatique a été demandée avec ce paiement. La configuration sécurisée est en cours de finalisation.",
    "recurringConsent": "Rechargez automatiquement ce même numéro tous les {days} jours avec votre carte enregistrée. Le total actuel est le maximum autorisé ; si le prix augmente, la recharge automatique est suspendue pour votre approbation.",
    "recurringConfirm": "Activer la recharge automatique",
    "everyDays": "Tous les {days} jours",
    "recurringFrequency": "Fréquence",
    "recurringNext": "Prochaine recharge",
    "recurringStatusACTIVE": "La recharge automatique est active.",
    "recurringStatusPAUSED": "La recharge automatique est suspendue.",
    "recurringStatusCANCELLED": "La recharge automatique est annulée.",
    "recurringPause": "Suspendre",
    "recurringResume": "Reprendre",
    "recurringCancel": "Annuler la recharge automatique",
    "recurringEnabled": "Recharge automatique activée.",
    "recurringPaused": "Recharge automatique suspendue.",
    "recurringResumed": "Recharge automatique reprise.",
    "recurringCancelled": "Recharge automatique annulée.",
    "recurringPaymentUnavailable": "Cette carte n’a pas été enregistrée pour la recharge automatique. Effectuez d’abord un nouveau paiement par carte, puis activez la recharge automatique.",
    "promo": "Code promotionnel",
    "apply": "Appliquer",
    "promotionApplied":
        "Promotion enregistrée. Demandez un nouveau devis pour vérifier les avantages.",
    "promotion": "Promotion",
    "originalFee": "Frais initiaux",
    "benefit": "Avantage promotionnel",
    "firstRecharge": "Première recharge admissible uniquement.",
    "nickname": "Enregistrer sous (facultatif)",
    "saved": "Destinataires enregistrés",
    "retry": "Réessayer",
    "refresh": "Vérifier le statut",
    "openCheckout": "Ouvrir Stripe Checkout sécurisé",
    "retrySame": "Réessayer la même tentative",
    "pendingNotice":
        "Paiement non résolu. Vérifiez le statut avant une autre recharge.",
    "history": "Historique",
    "receipt": "Reçu",
    "another": "Recharger un autre téléphone",
    "repeat": "Répéter avec un nouveau devis",
    "search": "Rechercher un pays",
    "close": "Fermer",
    "minimum": "Minimum",
    "maximum": "Maximum",
    "AIRTIME": "Crédit téléphonique",
    "DATA": "Données",
    "BUNDLE": "Forfait combiné",
    "PENDING": "En attente",
    "PROCESSING": "En cours",
    "DELIVERED": "Livrée",
    "FAILED": "Échec",
    "REFUNDED": "Remboursement confirmé",
    "VOIDED": "Annulation confirmée",
    "requestFailed":
        "Impossible de terminer. Réessayez ou consultez l’historique.",
    "quoteExpired": "Devis expiré. Demandez et vérifiez un nouveau devis.",
    "catalogChanged": "Catalogue modifié. Rechargez les produits et le devis.",
    "billingRequired": "Choisissez un pays de facturation avant de payer.",
    "accountRequired": "Connectez-vous ou créez un compte pour cette fonction.",
    "insufficientFunds": "Paiement refusé : fonds insuffisants.",
    "paymentDeclined": "Paiement refusé. Vérifiez vos coordonnées de paiement.",
    "resumeUnavailable":
        "Lien indisponible. Connectez-vous et consultez l’historique avant un autre paiement.",
    "share": "Partager FlupFlap",
    "copy": "Copier le lien",
    "copied": "Lien copié",
    "qr": "Scanner pour rejoindre FlupFlap",
    "referral": "Code de parrainage",
    "shareMessage": "Rejoignez FlupFlap avec mon code {code} : {url}",
    "emptyHistory": "Aucune recharge pour le moment.",
    "noProducts": "Aucun produit pris en charge disponible.",
    "unknownState": "Vérification du statut",
    "paymentCancelled": "Paiement annulé.",
    "providerFailed":
        "Recharge non livrée. Vérifiez le remboursement ou l’annulation.",
    "Conditions": "Conditions",
    "Airtime": "Crédit mobile",
    "Promotion": "Promotion",
    "or": "ou",
    "Create an account": "Créer un compte",
    "Create FlupFlap account": "Créer un compte FlupFlap",
    "Edit": "Modifier",
    "Number": "Numéro",
    "Amount": "Montant",
    "Pay": "Payer",
    "View all": "Tout afficher",
    "Minutes": "Minutes",
    "SMS": "SMS",
    "Unlimited": "Illimité",
    "Validity": "Validité",
    "hours": "heures",
    "days": "jours",
    "weeks": "semaines",
    "months": "mois",
    "years": "ans",
    "Sign in to FlupFlap": "Se connecter à FlupFlap",
    "Welcome": "Bienvenue",
    "Sign in to continue.": "Connectez-vous pour continuer.",
    "Language": "Langue",
    "Show": "Afficher",
    "Hide": "Masquer",
    "Password": "Mot de passe",
    "Show password": "Afficher le mot de passe",
    "Hide password": "Masquer le mot de passe",
    "First name": "Prénom",
    "Last name": "Nom",
    "Sign in": "Se connecter",
    "Create account": "Créer un compte",
    "Continue as guest": "Continuer en invité",
    "Sign out": "Se déconnecter",
    "Destination country": "Pays de destination",
    "FlupFlap": "FlupFlap",
    "Worldwide Mobile Recharge by TiCash-App":
        "Recharge mobile internationale par TiCash-App",
    "Destination": "Destination",
    "Phone number": "Numéro de téléphone",
    "Operator": "Opérateur",
    "Product": "Produit",
    "Recharge": "Recharge",
    "RECEIPT": "REÇU",
    "Reference": "Référence",
    "Status": "Statut",
    "Fee": "Frais",
    "Total": "Total",
    "Updated": "Mis à jour",
    "Support": "Assistance",
    "Privacy": "Confidentialité",
    "Terms": "Conditions",
    "pending": "en attente",
    "processing": "en cours",
    "delivered": "livrée",
    "failed": "échouée",
    "refunded": "remboursée",
    "Refresh": "Actualiser",
    "Home": "Accueil",
    "About": "À propos",
    "Security": "Sécurité",
    "Contact": "Contact",
    "Forgot password?": "Mot de passe oublié ?",
    "Guest": "Invité",
    "Country": "Pays",
    "Recipient": "Destinataire",
    "Continue": "Continuer",
    "Billing country": "Pays de facturation",
    "Automatic": "Automatique",
    "Cancel": "Annuler",
    "Delete": "Supprimer",
    "Pending": "En attente",
    "Processing": "En cours",
    "Delivered": "Livrée",
    "Successful": "Réussie",
    "Failed": "Échec",
    "Cancelled": "Annulée",
    "Refunded": "Remboursée",
    "Voided": "Paiement annulé",
    "Authorized": "Autorisé",
    "Activity unavailable": "Activité indisponible",
    "Already have an account? Sign in": "Déjà un compte ? Connectez-vous",
    "Check your connection and try again.":
        "Vérifiez votre connexion et réessayez.",
    "Choose a new secure password.":
        "Choisissez un nouveau mot de passe sécurisé.",
    "Enter a name, country and international phone number.":
        "Saisissez un nom, un pays et un numéro international.",
    "FAST • SIMPLE • WORLDWIDE": "RAPIDE • SIMPLE • INTERNATIONAL",
    "FlupFlap account": "Compte FlupFlap",
    "FlupFlap customer": "Client FlupFlap",
    "Guest recharge session": "Session de recharge invité",
    "If an account exists, reset instructions have been sent.":
        "Si le compte existe, les instructions ont été envoyées.",
    "No recharges yet": "Aucune recharge pour le moment",
    "No saved recipients yet": "Aucun destinataire enregistré",
    "Payments and recharge processing use protected server connections.":
        "Les paiements et recharges utilisent des connexions serveur protégées.",
    "Please wait…": "Veuillez patienter…",
    "Profile updated": "Profil mis à jour",
    "Pull down to try again.": "Tirez vers le bas pour réessayer.",
    "Quick access": "Accès rapide",
    "Recent activity": "Activité récente",
    "Recharge family and friends with supported mobile operators around the world.":
        "Rechargez vos proches auprès des opérateurs pris en charge dans le monde.",
    "Recharge phones worldwide in a few taps.":
        "Rechargez des téléphones dans le monde en quelques gestes.",
    "Recipient name": "Nom du destinataire",
    "Recipients unavailable": "Destinataires indisponibles",
    "Recipients you save during checkout will appear here for quick access.":
        "Les destinataires enregistrés lors du paiement apparaîtront ici.",
    "Reset FlupFlap password": "Réinitialiser le mot de passe FlupFlap",
    "Retry loading countries": "Recharger les pays",
    "Save people you recharge often": "Enregistrez vos destinataires fréquents",
    "Save profile": "Enregistrer le profil",
    "Save recipient": "Enregistrer le destinataire",
    "Saving…": "Enregistrement…",
    "Save someone during a recharge for faster sending next time.":
        "Enregistrez un destinataire lors d’une recharge pour la prochaine fois.",
    "Secure recharge": "Recharge sécurisée",
    "See history": "Voir l’historique",
    "Send a recharge": "Envoyer une recharge",
    "Send airtime": "Envoyer du crédit",
    "Sign in to continue to FlupFlap.":
        "Connectez-vous pour continuer sur FlupFlap.",
    "Start a recharge": "Commencer une recharge",
    "Start recharge": "Commencer la recharge",
    "This account is separate from your TiCash remittance account.":
        "Ce compte est distinct de votre compte de transfert TiCash.",
    "Track recharges": "Suivre les recharges",
    "Unable to complete this request. Check your details and try again.":
        "Impossible de terminer. Vérifiez les détails et réessayez.",
    "Unable to load recipients": "Impossible de charger les destinataires",
    "Unable to save recipient. Check the details and try again.":
        "Impossible d’enregistrer le destinataire. Vérifiez les détails.",
    "Unable to update profile": "Impossible de mettre à jour le profil",
    "Update password": "Modifier le mot de passe",
    "Use the 2-letter country code for your billing profile.":
        "Utilisez le code pays à 2 lettres de votre profil.",
    "Worldwide mobile recharge": "Recharge mobile internationale",
    "Your latest recharge will appear here.":
        "Votre dernière recharge apparaîtra ici.",
    "Your recharge history could not be loaded.":
        "Impossible de charger votre historique.",
    "Account": "Compte",
    "Recipients": "Destinataires",
    "Profile": "Profil",
    "Email": "E-mail",
  },
  "es": {
    "internetBundles": "Internet y paquetes",
    "internetBundlesHelp": "Elige un destino y operador para ver los planes disponibles.",
    "noInternetOperators": "No hay paquetes de internet para este destino.",
    "nationalPhoneHelp":
        "Introduce tu número local. Añadimos el prefijo del país automáticamente.",
    "invalidNationalPhone":
        "Introduce un número válido para el país seleccionado.",
    "havePromo": "¿Tienes un código promocional?",
    "promoUnavailable":
        "Este código no es válido, ha caducado o no está disponible para tu cuenta.",
    "promoSaved": "Código guardado: {name}",
    "copyCode": "Copiar código de referido",
    "copyReferralLink": "Copiar enlace de referido",
    "codeCopied": "Código de referido copiado",
    "shareAction": "Compartir",
    "guestReferral": "Crea una cuenta para obtener tu código de referido",
    "shareHelp": "Invita a alguien con tu código personal, enlace o código QR.",
    "pendingPayment": "Pago pendiente",
    "pendingRecoveryHelp":
        "Este pago aún no está resuelto. Comprueba su estado o cancélalo antes de iniciar otra recarga.",
    "cancelPending": "Cancelar el pago pendiente e iniciar una nueva recarga",
    "cancelledStartNew": "Pago cancelado. Puedes iniciar una nueva recarga.",
    "cancellationUnresolved":
        "Este pago aún no se puede cancelar de forma segura. Comprueba su estado antes de iniciar otra recarga.",
    "unconfirmedValue": "El proveedor no ha confirmado el valor entregado.",
    "quotedReceiver": "Valor cotizado para el destinatario",
    "receiverMismatch":
        "El valor entregado difiere de la cotización. Contacta con soporte.",
    "Country code": "Código de país",
    "No fixed expiry": "Sin vencimiento fijo",
    "REFUND_PENDING": "Reembolso pendiente",
    "VOID_PENDING": "Anulación pendiente",
    "Add recipient": "Añadir destinatario",
    "destination": "Destino",
    "operatorProduct": "Operador y producto",
    "reviewConfirm": "Revisar y confirmar",
    "recharge": "Recarga",
    "country": "País",
    "phone": "Número de teléfono internacional",
    "operator": "Operador",
    "product": "Producto",
    "continue": "Continuar",
    "back": "Atrás",
    "amount": "Importe de recarga",
    "amountInvalid": "Introduce un importe válido con hasta 2 decimales.",
    "amountTooLow": "Importe mínimo de recarga: {minimum}.",
    "amountTooHigh": "Importe máximo de recarga: {maximum}.",
    "amountPrecision": "Usa como máximo {precision} decimales.",
    "amountIncrement": "Usa incrementos de {increment} a partir de {minimum}.",
    "fee": "Comisión FlupFlap",
    "total": "Total",
    "receiver": "Valor recibido",
    "pendingValue": "Se confirma tras la entrega",
    "quoteExpiry": "El presupuesto vence",
    "reviewCheck": "He revisado el número, el producto y el total.",
    "pay": "Continuar al pago",
    "testPay": "Continuar al pago de prueba",
    "mockPay": "Confirmar recarga de prueba MOCK",
    "mockMode": "Prueba MOCK: sin pago ni recarga reales.",
    "sandboxMode": "Stripe sandbox: solo pago de prueba.",
    "billing": "País de facturación",
    "billingHelp": "El país del pagador puede diferir del destinatario.",
    "accountCountry": "Gestione su país de facturación en Cuenta.",
    "recurringTitle": "Recarga automática",
    "recurringHelp": "Elija cada 7, 15 o 30 días. FlupFlap cobra automáticamente a su tarjeta guardada y pausa el servicio si el precio aumenta o el pago requiere su atención.",
    "recurringReviewHelp": "Opcional: elija cada cuánto FlupFlap debe recargar automáticamente este mismo número después de que este pago se complete.",
    "recurringOff": "Recarga única",
    "recurringSetupPending": "Se solicitó la recarga automática con este pago. La configuración segura se está finalizando.",
    "recurringConsent": "Recargue automáticamente este mismo número cada {days} días con su tarjeta guardada. El total actual es el máximo permitido; si el precio aumenta, la recarga automática se pausa para su aprobación.",
    "recurringConfirm": "Activar recarga automática",
    "everyDays": "Cada {days} días",
    "recurringFrequency": "Frecuencia",
    "recurringNext": "Próxima recarga",
    "recurringStatusACTIVE": "La recarga automática está activa.",
    "recurringStatusPAUSED": "La recarga automática está pausada.",
    "recurringStatusCANCELLED": "La recarga automática está cancelada.",
    "recurringPause": "Pausar",
    "recurringResume": "Reanudar",
    "recurringCancel": "Cancelar recarga automática",
    "recurringEnabled": "Recarga automática activada.",
    "recurringPaused": "Recarga automática pausada.",
    "recurringResumed": "Recarga automática reanudada.",
    "recurringCancelled": "Recarga automática cancelada.",
    "recurringPaymentUnavailable": "Esta tarjeta no se guardó para recargas automáticas. Complete primero un nuevo pago con tarjeta y luego active la recarga automática.",
    "promo": "Código promocional",
    "apply": "Aplicar",
    "promotionApplied":
        "Promoción registrada. Solicite un nuevo presupuesto para revisar los beneficios.",
    "promotion": "Promoción",
    "originalFee": "Comisión original",
    "benefit": "Beneficio promocional",
    "firstRecharge": "Solo la primera recarga elegible.",
    "nickname": "Guardar destinatario como (opcional)",
    "saved": "Destinatarios guardados",
    "retry": "Reintentar",
    "refresh": "Consultar estado",
    "openCheckout": "Abrir Stripe Checkout seguro",
    "retrySame": "Reintentar el mismo pago",
    "pendingNotice":
        "Pago sin resolver. Consulte el estado antes de otra recarga.",
    "history": "Historial",
    "receipt": "Recibo",
    "another": "Recargar otro teléfono",
    "repeat": "Repetir con nuevo presupuesto",
    "search": "Buscar países",
    "close": "Cerrar",
    "minimum": "Mínimo",
    "maximum": "Máximo",
    "AIRTIME": "Saldo móvil",
    "DATA": "Datos",
    "BUNDLE": "Paquete",
    "PENDING": "Pendiente",
    "PROCESSING": "Procesando",
    "DELIVERED": "Entregado",
    "FAILED": "Fallido",
    "REFUNDED": "Reembolso confirmado",
    "VOIDED": "Anulación confirmada",
    "requestFailed": "No se pudo completar. Reintente o consulte el historial.",
    "quoteExpired": "Presupuesto vencido. Solicite y revise uno nuevo.",
    "catalogChanged": "El catálogo cambió. Actualice productos y presupuesto.",
    "billingRequired": "Seleccione un país de facturación antes de pagar.",
    "accountRequired": "Inicie sesión o cree una cuenta para esta función.",
    "insufficientFunds": "Pago rechazado: fondos insuficientes.",
    "paymentDeclined": "Pago rechazado. Revise sus datos de pago.",
    "resumeUnavailable":
        "Enlace no disponible. Inicie sesión y consulte el historial antes de otro pago.",
    "share": "Compartir FlupFlap",
    "copy": "Copiar enlace",
    "copied": "Enlace copiado",
    "qr": "Escanee para unirse a FlupFlap",
    "referral": "Código de referido",
    "shareMessage": "Únase a FlupFlap con mi código {code}: {url}",
    "emptyHistory": "Todavía no hay recargas.",
    "noProducts": "No hay productos compatibles disponibles.",
    "unknownState": "Consultando estado",
    "paymentCancelled": "Pago cancelado.",
    "providerFailed":
        "Recarga no entregada. Consulte el reembolso o la anulación.",
    "Conditions": "Condiciones",
    "Airtime": "Recarga móvil",
    "Promotion": "Promoción",
    "or": "o",
    "Create an account": "Crear una cuenta",
    "Create FlupFlap account": "Crear una cuenta FlupFlap",
    "Edit": "Editar",
    "Number": "Número",
    "Amount": "Importe",
    "Pay": "Pagar",
    "View all": "Ver todo",
    "Minutes": "Minutos",
    "SMS": "SMS",
    "Unlimited": "Ilimitado",
    "Validity": "Validez",
    "hours": "horas",
    "days": "días",
    "weeks": "semanas",
    "months": "meses",
    "years": "años",
    "Sign in to FlupFlap": "Iniciar sesión en FlupFlap",
    "Welcome": "Te damos la bienvenida",
    "Sign in to continue.": "Inicia sesión para continuar.",
    "Language": "Idioma",
    "Show": "Mostrar",
    "Hide": "Ocultar",
    "Password": "Contraseña",
    "Show password": "Mostrar contraseña",
    "Hide password": "Ocultar contraseña",
    "First name": "Nombre",
    "Last name": "Apellido",
    "Sign in": "Iniciar sesión",
    "Create account": "Crear una cuenta",
    "Continue as guest": "Continuar como invitado",
    "Sign out": "Cerrar sesión",
    "Destination country": "País de destino",
    "FlupFlap": "FlupFlap",
    "Worldwide Mobile Recharge by TiCash-App":
        "Recarga móvil mundial por TiCash-App",
    "Destination": "Destino",
    "Phone number": "Número de teléfono",
    "Operator": "Operador",
    "Product": "Producto",
    "Recharge": "Recarga",
    "RECEIPT": "RECIBO",
    "Reference": "Referencia",
    "Status": "Estado",
    "Fee": "Tarifa",
    "Total": "Total",
    "Updated": "Actualizado",
    "Support": "Ayuda",
    "Privacy": "Privacidad",
    "Terms": "Condiciones",
    "pending": "pendiente",
    "processing": "en proceso",
    "delivered": "entregada",
    "failed": "fallida",
    "refunded": "reembolsada",
    "Refresh": "Actualizar",
    "Home": "Inicio",
    "About": "Acerca de",
    "Security": "Seguridad",
    "Contact": "Contacto",
    "Forgot password?": "¿Olvidaste tu contraseña?",
    "Guest": "Invitado",
    "Country": "País",
    "Recipient": "Destinatario",
    "Continue": "Continuar",
    "Billing country": "País de facturación",
    "Automatic": "Automático",
    "Cancel": "Cancelar",
    "Delete": "Eliminar",
    "Pending": "Pendiente",
    "Processing": "Procesando",
    "Delivered": "Entregada",
    "Successful": "Correcta",
    "Failed": "Fallida",
    "Cancelled": "Cancelada",
    "Refunded": "Reembolsada",
    "Voided": "Pago anulado",
    "Authorized": "Autorizado",
    "Activity unavailable": "Actividad no disponible",
    "Already have an account? Sign in": "¿Ya tiene una cuenta? Inicie sesión",
    "Check your connection and try again.": "Revise su conexión y reintente.",
    "Choose a new secure password.": "Elija una nueva contraseña segura.",
    "Enter a name, country and international phone number.":
        "Introduzca nombre, país y número internacional.",
    "FAST • SIMPLE • WORLDWIDE": "RÁPIDO • SENCILLO • INTERNACIONAL",
    "FlupFlap account": "Cuenta FlupFlap",
    "FlupFlap customer": "Cliente FlupFlap",
    "Guest recharge session": "Sesión de recarga de invitado",
    "If an account exists, reset instructions have been sent.":
        "Si la cuenta existe, se enviaron instrucciones.",
    "No recharges yet": "Aún no hay recargas",
    "No saved recipients yet": "No hay destinatarios guardados",
    "Payments and recharge processing use protected server connections.":
        "Pagos y recargas usan conexiones protegidas.",
    "Please wait…": "Espere…",
    "Profile updated": "Perfil actualizado",
    "Pull down to try again.": "Deslice hacia abajo para reintentar.",
    "Quick access": "Acceso rápido",
    "Recent activity": "Actividad reciente",
    "Recharge family and friends with supported mobile operators around the world.":
        "Recargue a familiares y amigos con operadores compatibles del mundo.",
    "Recharge phones worldwide in a few taps.":
        "Recargue teléfonos del mundo en pocos pasos.",
    "Recipient name": "Nombre del destinatario",
    "Recipients unavailable": "Destinatarios no disponibles",
    "Recipients you save during checkout will appear here for quick access.":
        "Aquí aparecerán los destinatarios guardados durante el pago.",
    "Reset FlupFlap password": "Restablecer contraseña de FlupFlap",
    "Retry loading countries": "Volver a cargar países",
    "Save people you recharge often": "Guarde destinatarios frecuentes",
    "Save profile": "Guardar perfil",
    "Save recipient": "Guardar destinatario",
    "Saving…": "Guardando…",
    "Save someone during a recharge for faster sending next time.":
        "Guarde un destinatario durante la recarga para la próxima vez.",
    "Secure recharge": "Recarga segura",
    "See history": "Ver historial",
    "Send a recharge": "Enviar una recarga",
    "Send airtime": "Enviar saldo móvil",
    "Sign in to continue to FlupFlap.":
        "Inicie sesión para continuar en FlupFlap.",
    "Start a recharge": "Iniciar una recarga",
    "Start recharge": "Iniciar recarga",
    "This account is separate from your TiCash remittance account.":
        "Esta cuenta es independiente de su cuenta de remesas TiCash.",
    "Track recharges": "Seguir recargas",
    "Unable to complete this request. Check your details and try again.":
        "No se pudo completar. Revise los datos y reintente.",
    "Unable to load recipients": "No se pudieron cargar los destinatarios",
    "Unable to save recipient. Check the details and try again.":
        "No se pudo guardar el destinatario. Revise los datos.",
    "Unable to update profile": "No se pudo actualizar el perfil",
    "Update password": "Actualizar contraseña",
    "Use the 2-letter country code for your billing profile.":
        "Use el código de país de 2 letras para su perfil.",
    "Worldwide mobile recharge": "Recarga móvil mundial",
    "Your latest recharge will appear here.":
        "Su última recarga aparecerá aquí.",
    "Your recharge history could not be loaded.":
        "No se pudo cargar su historial.",
    "Account": "Cuenta",
    "Recipients": "Destinatarios",
    "Profile": "Perfil",
    "Email": "Correo electrónico",
  },
  "pt": {
    "internetBundles": "Internet e pacotes",
    "internetBundlesHelp": "Escolha um destino e uma operadora para ver os planos disponíveis.",
    "noInternetOperators": "Não há pacotes de internet para este destino.",
    "nationalPhoneHelp":
        "Digite seu número local. Adicionamos o código do país automaticamente.",
    "invalidNationalPhone": "Digite um número válido para o país selecionado.",
    "havePromo": "Tem um código promocional?",
    "promoUnavailable":
        "Este código é inválido, expirou ou não está disponível para sua conta.",
    "promoSaved": "Código salvo: {name}",
    "copyCode": "Copiar código de indicação",
    "copyReferralLink": "Copiar link de indicação",
    "codeCopied": "Código de indicação copiado",
    "shareAction": "Compartilhar",
    "guestReferral": "Crie uma conta para obter seu código de indicação",
    "shareHelp": "Convide alguém usando seu código pessoal, link ou código QR.",
    "pendingPayment": "Pagamento pendente",
    "pendingRecoveryHelp":
        "Este pagamento ainda não foi resolvido. Verifique o estado ou cancele-o antes de iniciar outra recarga.",
    "cancelPending": "Cancelar o pagamento pendente e iniciar uma nova recarga",
    "cancelledStartNew":
        "Pagamento cancelado. Você pode iniciar uma nova recarga.",
    "cancellationUnresolved":
        "Este pagamento ainda não pode ser cancelado com segurança. Verifique o estado antes de iniciar outra recarga.",
    "unconfirmedValue": "O provedor não confirmou o valor entregue.",
    "quotedReceiver": "Valor cotado para o destinatário",
    "receiverMismatch":
        "O valor entregue difere da cotação. Entre em contato com o suporte.",
    "Country code": "Código do país",
    "No fixed expiry": "Sem vencimento fixo",
    "REFUND_PENDING": "Reembolso pendente",
    "VOID_PENDING": "Anulação pendente",
    "Add recipient": "Adicionar destinatário",
    "destination": "Destino",
    "operatorProduct": "Operadora e produto",
    "reviewConfirm": "Revisar e confirmar",
    "recharge": "Recarga",
    "country": "País",
    "phone": "Número de telefone internacional",
    "operator": "Operadora",
    "product": "Produto",
    "continue": "Continuar",
    "back": "Voltar",
    "amount": "Valor da recarga",
    "amountInvalid": "Insira um valor válido com até 2 casas decimais.",
    "amountTooLow": "Valor mínimo da recarga: {minimum}.",
    "amountTooHigh": "Valor máximo da recarga: {maximum}.",
    "amountPrecision": "Use no máximo {precision} casas decimais.",
    "amountIncrement": "Use incrementos de {increment} a partir de {minimum}.",
    "fee": "Taxa FlupFlap",
    "total": "Total",
    "receiver": "Valor recebido",
    "pendingValue": "Confirmado após a entrega",
    "quoteExpiry": "A cotação expira",
    "reviewCheck": "Verifiquei o número, o produto e o total.",
    "pay": "Continuar para pagamento",
    "testPay": "Continuar para pagamento de teste",
    "mockPay": "Confirmar recarga de teste MOCK",
    "mockMode": "Teste MOCK: sem pagamento ou recarga reais.",
    "sandboxMode": "Stripe sandbox: apenas pagamento de teste.",
    "billing": "País de cobrança",
    "billingHelp": "O país do pagador pode ser diferente do destinatário.",
    "accountCountry": "Gerencie o país de cobrança em Conta.",
    "recurringTitle": "Recarga automática",
    "recurringHelp": "Escolha a cada 7, 15 ou 30 dias. O FlupFlap cobra automaticamente no cartão salvo e pausa o serviço se o preço aumentar ou o pagamento exigir sua atenção.",
    "recurringReviewHelp": "Opcional: escolha com que frequência o FlupFlap deve recarregar automaticamente este mesmo número após este pagamento ser concluído.",
    "recurringOff": "Recarga única",
    "recurringSetupPending": "A recarga automática foi solicitada com este pagamento. A configuração segura está sendo finalizada.",
    "recurringConsent": "Recarregue automaticamente este mesmo número a cada {days} dias usando seu cartão salvo. O total atual é o máximo permitido; se o preço aumentar, a recarga automática será pausada para sua aprovação.",
    "recurringConfirm": "Ativar recarga automática",
    "everyDays": "A cada {days} dias",
    "recurringFrequency": "Frequência",
    "recurringNext": "Próxima recarga",
    "recurringStatusACTIVE": "A recarga automática está ativa.",
    "recurringStatusPAUSED": "A recarga automática está pausada.",
    "recurringStatusCANCELLED": "A recarga automática está cancelada.",
    "recurringPause": "Pausar",
    "recurringResume": "Retomar",
    "recurringCancel": "Cancelar recarga automática",
    "recurringEnabled": "Recarga automática ativada.",
    "recurringPaused": "Recarga automática pausada.",
    "recurringResumed": "Recarga automática retomada.",
    "recurringCancelled": "Recarga automática cancelada.",
    "recurringPaymentUnavailable": "Este cartão não foi salvo para recarga automática. Primeiro conclua um novo pagamento com cartão e depois ative a recarga automática.",
    "promo": "Código promocional",
    "apply": "Aplicar",
    "promotionApplied":
        "Promoção registrada. Solicite nova cotação para revisar os benefícios.",
    "promotion": "Promoção",
    "originalFee": "Taxa original",
    "benefit": "Benefício promocional",
    "firstRecharge": "Apenas a primeira recarga elegível.",
    "nickname": "Salvar destinatário como (opcional)",
    "saved": "Destinatários salvos",
    "retry": "Tentar novamente",
    "refresh": "Verificar status",
    "openCheckout": "Abrir Stripe Checkout seguro",
    "retrySame": "Tentar o mesmo pagamento",
    "pendingNotice":
        "Pagamento pendente. Verifique o status antes de outra recarga.",
    "history": "Histórico",
    "receipt": "Recibo",
    "another": "Recarregar outro telefone",
    "repeat": "Repetir com nova cotação",
    "search": "Pesquisar países",
    "close": "Fechar",
    "minimum": "Mínimo",
    "maximum": "Máximo",
    "AIRTIME": "Crédito móvel",
    "DATA": "Dados",
    "BUNDLE": "Pacote",
    "PENDING": "Pendente",
    "PROCESSING": "Processando",
    "DELIVERED": "Entregue",
    "FAILED": "Falhou",
    "REFUNDED": "Reembolso confirmado",
    "VOIDED": "Anulação confirmada",
    "requestFailed":
        "Não foi possível concluir. Tente novamente ou consulte o histórico.",
    "quoteExpired": "Cotação expirada. Solicite e revise uma nova.",
    "catalogChanged": "O catálogo mudou. Atualize produtos e cotação.",
    "billingRequired": "Selecione um país de cobrança antes de pagar.",
    "accountRequired": "Entre ou crie uma conta para este recurso.",
    "insufficientFunds": "Pagamento recusado: saldo insuficiente.",
    "paymentDeclined": "Pagamento recusado. Verifique seus dados.",
    "resumeUnavailable":
        "Link indisponível. Entre e consulte o histórico antes de outro pagamento.",
    "share": "Compartilhar FlupFlap",
    "copy": "Copiar link",
    "copied": "Link copiado",
    "qr": "Escaneie para entrar no FlupFlap",
    "referral": "Código de indicação",
    "shareMessage": "Entre no FlupFlap com meu código {code}: {url}",
    "emptyHistory": "Ainda não há recargas.",
    "noProducts": "Nenhum produto compatível disponível.",
    "unknownState": "Verificando status",
    "paymentCancelled": "Pagamento cancelado.",
    "providerFailed":
        "Recarga não entregue. Verifique o reembolso ou a anulação.",
    "Conditions": "Condições",
    "Airtime": "Recarga de celular",
    "Promotion": "Promoção",
    "or": "ou",
    "Create an account": "Criar conta",
    "Create FlupFlap account": "Criar conta FlupFlap",
    "Edit": "Editar",
    "Number": "Número",
    "Amount": "Valor",
    "Pay": "Pagar",
    "View all": "Ver tudo",
    "Minutes": "Minutos",
    "SMS": "SMS",
    "Unlimited": "Ilimitado",
    "Validity": "Validade",
    "hours": "horas",
    "days": "dias",
    "weeks": "semanas",
    "months": "meses",
    "years": "anos",
    "Sign in to FlupFlap": "Entrar no FlupFlap",
    "Welcome": "Boas-vindas",
    "Sign in to continue.": "Entre para continuar.",
    "Language": "Idioma",
    "Show": "Mostrar",
    "Hide": "Ocultar",
    "Password": "Senha",
    "Show password": "Mostrar senha",
    "Hide password": "Ocultar senha",
    "First name": "Nome",
    "Last name": "Sobrenome",
    "Sign in": "Entrar",
    "Create account": "Criar conta",
    "Continue as guest": "Continuar como visitante",
    "Sign out": "Sair",
    "Destination country": "País de destino",
    "FlupFlap": "FlupFlap",
    "Worldwide Mobile Recharge by TiCash-App":
        "Recarga móvel mundial por TiCash-App",
    "Destination": "Destino",
    "Phone number": "Número de telefone",
    "Operator": "Operadora",
    "Product": "Produto",
    "Recharge": "Recarga",
    "RECEIPT": "RECIBO",
    "Reference": "Referência",
    "Status": "Status",
    "Fee": "Taxa",
    "Total": "Total",
    "Updated": "Atualizado",
    "Support": "Ajuda",
    "Privacy": "Privacidade",
    "Terms": "Termos",
    "pending": "pendente",
    "processing": "em processamento",
    "delivered": "entregue",
    "failed": "falhou",
    "refunded": "reembolsada",
    "Refresh": "Atualizar",
    "Home": "Início",
    "About": "Sobre",
    "Security": "Segurança",
    "Contact": "Contato",
    "Forgot password?": "Esqueceu a senha?",
    "Guest": "Visitante",
    "Country": "País",
    "Recipient": "Destinatário",
    "Continue": "Continuar",
    "Billing country": "País de cobrança",
    "Automatic": "Automático",
    "Cancel": "Cancelar",
    "Delete": "Excluir",
    "Pending": "Pendente",
    "Processing": "Processando",
    "Delivered": "Entregue",
    "Successful": "Concluída",
    "Failed": "Falhou",
    "Cancelled": "Cancelada",
    "Refunded": "Reembolsada",
    "Voided": "Pagamento anulado",
    "Authorized": "Autorizado",
    "Activity unavailable": "Atividade indisponível",
    "Already have an account? Sign in": "Já tem uma conta? Entre",
    "Check your connection and try again.":
        "Verifique a conexão e tente novamente.",
    "Choose a new secure password.": "Escolha uma nova senha segura.",
    "Enter a name, country and international phone number.":
        "Insira nome, país e número internacional.",
    "FAST • SIMPLE • WORLDWIDE": "RÁPIDO • SIMPLES • GLOBAL",
    "FlupFlap account": "Conta FlupFlap",
    "FlupFlap customer": "Cliente FlupFlap",
    "Guest recharge session": "Sessão de recarga de visitante",
    "If an account exists, reset instructions have been sent.":
        "Se a conta existir, as instruções foram enviadas.",
    "No recharges yet": "Ainda não há recargas",
    "No saved recipients yet": "Nenhum destinatário salvo",
    "Payments and recharge processing use protected server connections.":
        "Pagamentos e recargas usam conexões protegidas.",
    "Please wait…": "Aguarde…",
    "Profile updated": "Perfil atualizado",
    "Pull down to try again.": "Puxe para baixo para tentar novamente.",
    "Quick access": "Acesso rápido",
    "Recent activity": "Atividade recente",
    "Recharge family and friends with supported mobile operators around the world.":
        "Recarregue familiares e amigos com operadoras compatíveis no mundo.",
    "Recharge phones worldwide in a few taps.":
        "Recarregue telefones no mundo em poucos toques.",
    "Recipient name": "Nome do destinatário",
    "Recipients unavailable": "Destinatários indisponíveis",
    "Recipients you save during checkout will appear here for quick access.":
        "Os destinatários salvos no pagamento aparecerão aqui.",
    "Reset FlupFlap password": "Redefinir senha do FlupFlap",
    "Retry loading countries": "Recarregar países",
    "Save people you recharge often": "Salve destinatários frequentes",
    "Save profile": "Salvar perfil",
    "Save recipient": "Salvar destinatário",
    "Saving…": "Salvando…",
    "Save someone during a recharge for faster sending next time.":
        "Salve um destinatário na recarga para a próxima vez.",
    "Secure recharge": "Recarga segura",
    "See history": "Ver histórico",
    "Send a recharge": "Enviar uma recarga",
    "Send airtime": "Enviar crédito móvel",
    "Sign in to continue to FlupFlap.": "Entre para continuar no FlupFlap.",
    "Start a recharge": "Iniciar uma recarga",
    "Start recharge": "Iniciar recarga",
    "This account is separate from your TiCash remittance account.":
        "Esta conta é separada da sua conta de remessas TiCash.",
    "Track recharges": "Acompanhar recargas",
    "Unable to complete this request. Check your details and try again.":
        "Não foi possível concluir. Verifique os dados e tente novamente.",
    "Unable to load recipients": "Não foi possível carregar destinatários",
    "Unable to save recipient. Check the details and try again.":
        "Não foi possível salvar o destinatário. Verifique os dados.",
    "Unable to update profile": "Não foi possível atualizar o perfil",
    "Update password": "Atualizar senha",
    "Use the 2-letter country code for your billing profile.":
        "Use o código de país de 2 letras no perfil.",
    "Worldwide mobile recharge": "Recarga móvel mundial",
    "Your latest recharge will appear here.":
        "Sua última recarga aparecerá aqui.",
    "Your recharge history could not be loaded.":
        "Não foi possível carregar seu histórico.",
    "Account": "Conta",
    "Recipients": "Destinatários",
    "Profile": "Perfil",
    "Email": "E-mail",
  },
};
