const Map<String, Map<String, String>> privacyStrings = {
  "en": {
    "Privacy policy": "Privacy policy",
    "Delete my account": "Delete my account",
    "Request deletion of your FlupFlap account and associated data": "Request deletion of your FlupFlap account and associated data",
    "Delete my FlupFlap account": "Delete my FlupFlap account",
    "Request account and data deletion": "Request account and data deletion",
    "Email us from the address registered to your FlupFlap account. Ask to delete your account and associated personal data. If you cannot access that email address, explain this so support can help verify your request.": "Email us from the address registered to your FlupFlap account. Ask to delete your account and associated personal data. If you cannot access that email address, explain this so support can help verify your request.",
    "Write deletion request": "Write deletion request",
    "Copy email address": "Copy email address",
    "Opening your email app does not send a request. Review and send the email yourself. Do not include passwords, payment card details or identity documents.": "Opening your email app does not send a request. Review and send the email yourself. Do not include passwords, payment card details or identity documents.",
    "Support reviews and verifies requests before processing deletion. Ask support to stop any recurring recharges as part of your request. Deleting a receipt or signing out does not delete your account. Certain transaction, security or audit records may need to be retained for legitimate reasons; support can explain any applicable retention.": "Support reviews and verifies requests before processing deletion. Ask support to stop any recurring recharges as part of your request. Deleting a receipt or signing out does not delete your account. Certain transaction, security or audit records may need to be retained for legitimate reasons; support can explain any applicable retention.",
    "Open deletion webpage": "Open deletion webpage",
    "Unable to open. Email contact@ticash-app.com for help.": "Unable to open. Email contact@ticash-app.com for help.",
    "Unable to open. Copy the email address and send your request manually.": "Unable to open. Copy the email address and send your request manually.",
    "Email address copied": "Email address copied"
  },
  "fr": {
    "Privacy policy": "Politique de confidentialité",
    "Delete my account": "Supprimer mon compte",
    "Request deletion of your FlupFlap account and associated data": "Demander la suppression de votre compte FlupFlap et des données associées",
    "Delete my FlupFlap account": "Supprimer mon compte FlupFlap",
    "Request account and data deletion": "Demander la suppression du compte et des données",
    "Email us from the address registered to your FlupFlap account. Ask to delete your account and associated personal data. If you cannot access that email address, explain this so support can help verify your request.": "Écrivez-nous depuis l’adresse enregistrée sur votre compte FlupFlap. Demandez la suppression de votre compte et des données personnelles associées. Si vous ne pouvez plus accéder à cette adresse, expliquez-le pour que le support vous aide à vérifier la demande.",
    "Write deletion request": "Rédiger une demande de suppression",
    "Copy email address": "Copier l’adresse e-mail",
    "Opening your email app does not send a request. Review and send the email yourself. Do not include passwords, payment card details or identity documents.": "Ouvrir votre messagerie ne soumet pas la demande. Vérifiez et envoyez vous-même le message. Ne joignez pas de mot de passe, de coordonnées de carte ou de pièce d’identité.",
    "Support reviews and verifies requests before processing deletion. Ask support to stop any recurring recharges as part of your request. Deleting a receipt or signing out does not delete your account. Certain transaction, security or audit records may need to be retained for legitimate reasons; support can explain any applicable retention.": "Le support examine et vérifie les demandes avant la suppression. Demandez aussi l’arrêt des recharges récurrentes. Supprimer un reçu ou se déconnecter ne supprime pas le compte. Certaines données de transaction, de sécurité ou d’audit peuvent être conservées pour des raisons légitimes ; le support peut expliquer les règles applicables.",
    "Open deletion webpage": "Ouvrir la page de suppression",
    "Unable to open. Email contact@ticash-app.com for help.": "Ouverture impossible. Écrivez à contact@ticash-app.com pour obtenir de l’aide.",
    "Unable to open. Copy the email address and send your request manually.": "Ouverture impossible. Copiez l’adresse e-mail et envoyez votre demande manuellement.",
    "Email address copied": "Adresse e-mail copiée"
  },
  "ht": {
    "Privacy policy": "Règleman sou vi prive",
    "Delete my account": "Efase kont mwen",
    "Request deletion of your FlupFlap account and associated data": "Mande pou efase kont FlupFlap ou ak done ki asosye avè l",
    "Delete my FlupFlap account": "Efase kont FlupFlap mwen",
    "Request account and data deletion": "Mande pou efase kont ak done",
    "Email us from the address registered to your FlupFlap account. Ask to delete your account and associated personal data. If you cannot access that email address, explain this so support can help verify your request.": "Ekri nou depi adrès imel ki anrejistre sou kont FlupFlap ou a. Mande pou efase kont ou ak done pèsonèl ki asosye avè l. Si ou pa ka jwenn aksè nan imel sa a, esplike sa pou sipò a ede verifye demann ou an.",
    "Write deletion request": "Ekri demann pou efase kont",
    "Copy email address": "Kopye adrès imel la",
    "Opening your email app does not send a request. Review and send the email yourself. Do not include passwords, payment card details or identity documents.": "Louvri aplikasyon imel ou a pa voye demann nan. Verifye epi voye imel la ou menm. Pa mete modpas, enfòmasyon kat peman oswa dokiman idantite ladan l.",
    "Support reviews and verifies requests before processing deletion. Ask support to stop any recurring recharges as part of your request. Deleting a receipt or signing out does not delete your account. Certain transaction, security or audit records may need to be retained for legitimate reasons; support can explain any applicable retention.": "Sipò a egzamine epi verifye demann yo anvan li trete efasman an. Mande pou sispann rechaj otomatik yo tou. Efase yon resi oswa dekonekte pa efase kont ou. Gen kèk dosye tranzaksyon, sekirite oswa verifikasyon ki ka rete pou rezon lejitim; sipò a ka esplike règleman sa yo.",
    "Open deletion webpage": "Louvri paj efasman an",
    "Unable to open. Email contact@ticash-app.com for help.": "Pa ka louvri. Ekri contact@ticash-app.com pou jwenn èd.",
    "Unable to open. Copy the email address and send your request manually.": "Pa ka louvri. Kopye adrès imel la epi voye demann ou an ou menm.",
    "Email address copied": "Adrès imel la kopye"
  },
  "es": {
    "Privacy policy": "Política de privacidad",
    "Delete my account": "Eliminar mi cuenta",
    "Request deletion of your FlupFlap account and associated data": "Solicitar la eliminación de tu cuenta FlupFlap y los datos asociados",
    "Delete my FlupFlap account": "Eliminar mi cuenta FlupFlap",
    "Request account and data deletion": "Solicitar eliminación de cuenta y datos",
    "Email us from the address registered to your FlupFlap account. Ask to delete your account and associated personal data. If you cannot access that email address, explain this so support can help verify your request.": "Escríbenos desde el correo registrado en tu cuenta FlupFlap. Solicita eliminar tu cuenta y los datos personales asociados. Si no puedes acceder a ese correo, explícalo para que soporte te ayude a verificar la solicitud.",
    "Write deletion request": "Redactar solicitud de eliminación",
    "Copy email address": "Copiar correo electrónico",
    "Opening your email app does not send a request. Review and send the email yourself. Do not include passwords, payment card details or identity documents.": "Abrir tu aplicación de correo no envía la solicitud. Revisa y envía tú mismo el mensaje. No incluyas contraseñas, datos de tarjetas ni documentos de identidad.",
    "Support reviews and verifies requests before processing deletion. Ask support to stop any recurring recharges as part of your request. Deleting a receipt or signing out does not delete your account. Certain transaction, security or audit records may need to be retained for legitimate reasons; support can explain any applicable retention.": "Soporte revisa y verifica las solicitudes antes de procesar la eliminación. Solicita también detener las recargas recurrentes. Eliminar un recibo o cerrar sesión no elimina tu cuenta. Algunos registros de transacciones, seguridad o auditoría pueden conservarse por motivos legítimos; soporte puede explicar la retención aplicable.",
    "Open deletion webpage": "Abrir página de eliminación",
    "Unable to open. Email contact@ticash-app.com for help.": "No se pudo abrir. Escribe a contact@ticash-app.com para obtener ayuda.",
    "Unable to open. Copy the email address and send your request manually.": "No se pudo abrir. Copia el correo y envía la solicitud manualmente.",
    "Email address copied": "Correo electrónico copiado"
  },
  "pt": {
    "Privacy policy": "Política de privacidade",
    "Delete my account": "Excluir minha conta",
    "Request deletion of your FlupFlap account and associated data": "Solicitar a exclusão da conta FlupFlap e dos dados associados",
    "Delete my FlupFlap account": "Excluir minha conta FlupFlap",
    "Request account and data deletion": "Solicitar exclusão da conta e dos dados",
    "Email us from the address registered to your FlupFlap account. Ask to delete your account and associated personal data. If you cannot access that email address, explain this so support can help verify your request.": "Escreva usando o e-mail registrado na sua conta FlupFlap. Solicite a exclusão da conta e dos dados pessoais associados. Se não tiver acesso a esse e-mail, explique para que o suporte ajude a verificar a solicitação.",
    "Write deletion request": "Escrever solicitação de exclusão",
    "Copy email address": "Copiar endereço de e-mail",
    "Opening your email app does not send a request. Review and send the email yourself. Do not include passwords, payment card details or identity documents.": "Abrir seu aplicativo de e-mail não envia a solicitação. Revise e envie a mensagem você mesmo. Não inclua senhas, dados de cartão ou documentos de identidade.",
    "Support reviews and verifies requests before processing deletion. Ask support to stop any recurring recharges as part of your request. Deleting a receipt or signing out does not delete your account. Certain transaction, security or audit records may need to be retained for legitimate reasons; support can explain any applicable retention.": "O suporte analisa e verifica as solicitações antes da exclusão. Peça também a interrupção das recargas recorrentes. Excluir um recibo ou sair não exclui a conta. Alguns registros de transações, segurança ou auditoria podem ser mantidos por motivos legítimos; o suporte pode explicar a retenção aplicável.",
    "Open deletion webpage": "Abrir página de exclusão",
    "Unable to open. Email contact@ticash-app.com for help.": "Não foi possível abrir. Escreva para contact@ticash-app.com para obter ajuda.",
    "Unable to open. Copy the email address and send your request manually.": "Não foi possível abrir. Copie o e-mail e envie a solicitação manualmente.",
    "Email address copied": "Endereço de e-mail copiado"
  }
};
