services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ticash
      POSTGRES_PASSWORD: ticash
      POSTGRES_DB: ticash
    ports:
      - "5432:5432"
    volumes:
      - ticash_pg:/var/lib/postgresql/data
volumes:
  ticash_pg:
