import 'package:flutter/material.dart';

enum AppLanguage {
  english('en', 'English'),
  spanish('es', 'Español'),
  french('fr', 'Français'),
  haitianCreole('ht', 'Kreyòl ayisyen'),
  portuguese('pt', 'Português');

  const AppLanguage(this.code, this.nativeName);

  final String code;
  final String nativeName;

  Locale get materialLocale => Locale(code == 'ht' ? 'fr' : code);

  static AppLanguage fromCode(String? code) => AppLanguage.values.firstWhere(
    (language) => language.code == code,
    orElse: () => AppLanguage.english,
  );
}

class AppLocalizationScope extends InheritedWidget {
  const AppLocalizationScope({
    super.key,
    required this.language,
    required super.child,
  });

  final AppLanguage language;

  static AppLocalizationScope of(BuildContext context) {
    final scope = context
        .dependOnInheritedWidgetOfExactType<AppLocalizationScope>();
    assert(scope != null, 'No AppLocalizationScope found in context.');
    return scope!;
  }

  @override
  bool updateShouldNotify(AppLocalizationScope oldWidget) =>
      language != oldWidget.language;
}

extension TiCashTranslations on BuildContext {
  AppLanguage get appLanguage => AppLocalizationScope.of(this).language;

  String tr(String key, [Map<String, Object?> values = const {}]) {
    var text =
        _translations[appLanguage]?[key] ??
        _translations[AppLanguage.english]?[key] ??
        key;
    for (final entry in values.entries) {
      text = text.replaceAll('{${entry.key}}', '${entry.value}');
    }
    return text;
  }
}

const Map<AppLanguage, Map<String, String>> _translations = {
  AppLanguage.english: {
    'language': 'Language',
    'changeLanguage': 'Change language',
    'chooseLanguage': 'Choose your language',
    'back': 'Back',
    'close': 'Close',
    'home': 'Home',
    'recipients': 'Recipients',
    'transfers': 'Transfers',
    'profile': 'Profile',
    'retry': 'Retry',
    'tryAgain': 'Try again',
    'cancel': 'Cancel',
    'save': 'Save',
    'update': 'Update',
    'continue': 'Continue',
    'required': 'Required',
    'welcomeBack': 'Welcome back',
    'signInSubtitle': 'Sign in to manage recipients and track your transfers.',
    'emailAddress': 'Email address',
    'enterValidEmail': 'Enter a valid email address',
    'password': 'Password',
    'showPassword': 'Show password',
    'hidePassword': 'Hide password',
    'passwordMin': 'Password must be at least 8 characters',
    'passwordRecoveryUnavailable': 'Password recovery is not connected yet.',
    'forgotPassword': 'Forgot password?',
    'signIn': 'Sign in',
    'newToTiCash': 'New to TiCash?',
    'createAccount': 'Create account',
    'sessionSecure': 'Your session is stored securely on this device',
    'startWithTiCash': 'Start with TiCash',
    'registerSubtitle':
        'Create your account. Identity review is required before transfers.',
    'firstName': 'First name',
    'lastName': 'Last name',
    'useAtLeast8': 'Use at least 8 characters',
    'testBuildDisclosure':
        'By continuing, you acknowledge that live funding and payouts are not enabled in this test build.',
    'hiName': 'Hi, {name}',
    'there': 'there',
    'sendSupportHome': 'Send support home',
    'quoteSubtitle':
        'See your exchange rate, fees, and recipient amount before you send.',
    'startTransfer': 'Start a transfer',
    'transferSummaryUnavailable': 'Transfer summary is unavailable.',
    'viewAll': 'View all',
    'recipientsLoadFailed': 'Recipients could not be loaded.',
    'noRecipients': 'No recipients yet',
    'addRecipientBeforeTransfer': 'Add a recipient before your first transfer.',
    'add': 'Add',
    'haitiWallet': 'Haiti wallet',
    'recentTransfers': 'Recent transfers',
    'seeHistory': 'See history',
    'noTransfers': 'No transfers yet',
    'submittedTransfersHere': 'Your submitted transfers will appear here.',
    'send': 'Send',
    'usdSubmitted': 'USD submitted',
    'inProgress': 'In progress',
    'newTransfer': 'New transfer',
    'historyUnavailable': 'Transfer history is unavailable.',
    'historyEmptyBody':
        'Completed and pending transfers will appear here after submission.',
    'transferHistory': 'Transfer history',
    'transferHistoryBody':
        'Tap any transfer to view its receipt and provider reference.',
    'addRecipient': 'Add recipient',
    'peopleYouSupport': 'People you support',
    'recipientsSubtitle':
        'Save verified Haiti contact and payout details for faster transfers.',
    'searchNamePhone': 'Search name or phone',
    'noMatchingRecipients': 'No recipients match your search.',
    'edit': 'Edit',
    'delete': 'Delete',
    'deleteRecipient': 'Delete recipient?',
    'removeRecipient': 'Remove {name} from your saved recipients?',
    'recipientNotDeleted': 'Recipient was not deleted.',
    'editRecipient': 'Edit recipient',
    'fullName': 'Full name',
    'haitiPhone': 'Haiti phone number',
    'streetAddress': 'Street address',
    'city': 'City',
    'department': 'Department',
    'deliveryWallet': 'Delivery wallet',
    'saveRecipient': 'Save recipient',
    'saveChanges': 'Save changes',
    'recipientSaveFailed': 'Recipient could not be saved.',
    'helpSafety': 'Help & safety',
    'sandboxNotice':
        'This build operates in sandbox mode. It records test transfers but does not collect real funding or submit live MonCash or NatCash payouts.',
    'protectAccount': 'Protect your account',
    'protectAccountBody':
        'Never share your password or verification codes. TiCash support should never ask you to send money to unlock an account.',
    'transferAssistance': 'Transfer assistance',
    'transferAssistanceBody':
        'Open Transfers, select the transfer, and retain its reference. Live refunds and disputes require approved provider procedures before launch.',
    'privacy': 'Privacy',
    'privacyBody':
        'Account and transfer data are stored by the configured TiCash API. Do not upload identity documents until an approved encrypted KYC provider is connected.',
    'termsFees': 'Terms and fees',
    'termsFeesBody':
        'Displayed exchange rates and fees are sandbox values. Final terms, privacy notice, refund policy, and fee schedule require legal approval before release.',
    'testingHelp':
        'For testing issues, contact the TiCash development administrator and provide only the transfer reference—never your password.',
    'wallet': 'Wallet',
    'transferAccount': 'TiCash transfer account',
    'noStoredBalance': 'No stored balance',
    'loadingActivity': 'Loading transfer activity…',
    'transfersRecorded': '{count} transfers recorded',
    'fundingStatus': 'Funding status',
    'fundingNotConnected': 'Card and bank funding are not connected',
    'fundingProviderRequired':
        'Live funding requires an approved payment provider',
    'qrUnavailable': 'QR receiving is unavailable',
    'sandboxNoFunds': 'TiCash does not hold customer funds in sandbox mode',
    'sendToHaiti': 'Send to Haiti',
    'guest': 'Guest',
    'identityReview': 'Identity review',
    'unknown': 'unknown',
    'personalInformation': 'Personal information',
    'addMobile': 'Add your mobile number',
    'identityVerification': 'Identity verification',
    'requestManualReview': 'Request a secure manual review',
    'changePassword': 'Change password',
    'changePasswordSubtitle': 'Update your sign-in password securely',
    'helpSubtitle': 'Sandbox status, privacy, and transfer help',
    'adminDashboard': 'Open admin dashboard',
    'logOut': 'Log out',
    'currentPassword': 'Current password',
    'newPassword': 'New password',
    'confirmNewPassword': 'Confirm new password',
    'passwordsDoNotMatch': 'The new passwords do not match.',
    'passwordChanged': 'Password changed. Please sign in again.',
    'editProfile': 'Edit profile',
    'mobilePhone': 'Mobile phone',
    'includeCountryCode': 'Include the country code',
    'profileUpdated': 'Profile updated.',
    'requestIdentityReview': 'Request identity review',
    'requestReview': 'Request review',
    'identityReviewRequested': 'Identity review requested.',
    'transferReceipt': 'Transfer receipt',
    'status': 'Status',
    'recipient': 'Recipient',
    'delivery': 'Delivery',
    'youSend': 'You send',
    'fee': 'Fee',
    'exchangeRate': 'Exchange rate',
    'recipientReceives': 'Recipient receives',
    'reference': 'Reference',
    'created': 'Created',
    'completed': 'COMPLETED',
    'failed': 'FAILED',
    'cancelled': 'CANCELLED',
    'reversed': 'REVERSED',
    'processing': 'PROCESSING',
    'pending': 'PENDING',
    'amount': 'Amount',
    'deliveryStep': 'Delivery',
    'payment': 'Payment',
    'review': 'Review',
    'done': 'Done',
    'amountError': 'Enter an amount between 1 and 10,000 USD.',
    'recipientError':
        'Complete all recipient details using a valid Haiti phone number.',
    'quoteUnavailable':
        'The quote service is unavailable. No transfer has been submitted.',
    'transferNotSubmitted':
        'The transfer was not submitted. Retrying will keep the same request reference.',
    'confirmSend': 'Confirm & send',
    'howMuch': 'How much are you sending?',
    'amountSubtitle':
        'Enter USD. Fees and the HTG amount are calculated by TiCash before review.',
    'whoReceiving': 'Who is receiving?',
    'recipientLegal':
        'Use the recipient’s legal name and Haiti contact details.',
    'haitiPhoneHelper': '+509 followed by 8 digits',
    'chooseDelivery': 'Choose delivery',
    'deliverySubtitle':
        'Select the wallet associated with the recipient’s Haiti phone number.',
    'mobileWalletDelivery': 'Mobile wallet delivery',
    'availabilityTiming':
        'Availability and timing depend on approved provider integrations.',
    'paymentSubtitle':
        'Review the funding status before requesting your quote.',
    'testMode': 'Test mode',
    'noCharge':
        'No card or bank account will be charged. Live funding is not connected in this build.',
    'usdRequested': '{amount} USD requested',
    'reviewTransfer': 'Review transfer',
    'reviewSubtitle':
        'These values came from the TiCash API. Confirm every detail before submitting.',
    'phone': 'Phone',
    'total': 'Total',
    'recipientGets': 'Recipient gets',
    'testRecordNotice':
        'Submitting creates a test-mode transfer record. No real money moves.',
    'transferSubmitted': 'Transfer submitted',
    'transferSuccessBody':
        'Your test-mode transfer record was created successfully.',
    'youSent': 'You sent',
    'viewTransfers': 'View transfers',
    'sendAnother': 'Send another transfer',
    'stepProgress': 'Step {current} of {total} • {label}',
    'identityRequired': 'Identity review required',
    'identityPending': 'Your identity review is pending.',
    'openProfileReview':
        'Open your profile to request the available manual review.',
    'openProfile': 'Open profile',
    'preparingSession': 'Preparing your secure session',
    'walletGeneric': 'Wallet',
    'identityReviewExplanation':
        'TiCash will place your account in manual review. Identity documents must be provided through an approved secure verification provider before live transfers are enabled.',
    'beforeVerification': 'Before you begin',
    'governmentIdRequired': 'Have a valid government-issued ID ready.',
    'cameraRequired': 'Allow camera access when Didit requests it.',
    'goodLightingRequired': 'Use a well-lit, private place.',
    'diditDisclosure':
        'Identity verification is provided by Didit. TiCash does not store document or selfie images from this flow. Access is granted only after the TiCash server confirms the result.',
    'continueVerification': 'Continue verification',
    'startVerification': 'Start identity verification',
    'checkVerificationStatus': 'Check verification status',
    'verifyYourIdentity': 'Verify your identity',
    'verifyIdentityBody':
        'Secure identity verification is required before real-money transfers can be enabled.',
    'verificationStarted': 'Verification started',
    'verificationStartedBody':
        'Continue the secure verification flow, or check for an updated result.',
    'verificationInReview': 'Verification in review',
    'verificationInReviewBody':
        'Didit is reviewing your verification. TiCash will update your account after the server receives a confirmed result.',
    'verificationApproved': 'Identity verified',
    'verificationApprovedBody':
        'Your identity verification was approved by the TiCash backend.',
    'verificationDeclined': 'Verification not approved',
    'verificationDeclinedBody':
        'The verification could not be approved. You may start a new verification or contact support.',
    'verificationExpired': 'Verification expired',
    'verificationExpiredBody':
        'This verification session expired. Start a new secure session to continue.',
    'openIdentityVerification':
        'Complete secure identity verification before starting a transfer.',
    'verifyIdentity': 'Verify identity',
  },
  AppLanguage.spanish: {
    'language': 'Idioma',
    'changeLanguage': 'Cambiar idioma',
    'chooseLanguage': 'Elige tu idioma',
    'back': 'Atrás',
    'close': 'Cerrar',
    'home': 'Inicio',
    'recipients': 'Destinatarios',
    'transfers': 'Transferencias',
    'profile': 'Perfil',
    'retry': 'Reintentar',
    'tryAgain': 'Intentar de nuevo',
    'cancel': 'Cancelar',
    'save': 'Guardar',
    'update': 'Actualizar',
    'continue': 'Continuar',
    'required': 'Obligatorio',
    'welcomeBack': 'Bienvenido de nuevo',
    'signInSubtitle':
        'Inicia sesión para administrar destinatarios y seguir tus transferencias.',
    'emailAddress': 'Correo electrónico',
    'enterValidEmail': 'Ingresa un correo válido',
    'password': 'Contraseña',
    'showPassword': 'Mostrar contraseña',
    'hidePassword': 'Ocultar contraseña',
    'passwordMin': 'La contraseña debe tener al menos 8 caracteres',
    'passwordRecoveryUnavailable':
        'La recuperación de contraseña aún no está conectada.',
    'forgotPassword': '¿Olvidaste tu contraseña?',
    'signIn': 'Iniciar sesión',
    'newToTiCash': '¿Nuevo en TiCash?',
    'createAccount': 'Crear cuenta',
    'sessionSecure': 'Tu sesión se guarda de forma segura en este dispositivo',
    'startWithTiCash': 'Comienza con TiCash',
    'registerSubtitle':
        'Crea tu cuenta. Se requiere revisión de identidad antes de transferir.',
    'firstName': 'Nombre',
    'lastName': 'Apellido',
    'useAtLeast8': 'Usa al menos 8 caracteres',
    'testBuildDisclosure':
        'Al continuar, reconoces que los fondos y pagos reales no están habilitados en esta versión de prueba.',
    'hiName': 'Hola, {name}',
    'there': 'amigo',
    'sendSupportHome': 'Envía apoyo a casa',
    'quoteSubtitle':
        'Obtén una cotización USD a HTG calculada por el servidor antes de enviar.',
    'startTransfer': 'Iniciar transferencia',
    'transferSummaryUnavailable':
        'El resumen de transferencias no está disponible.',
    'viewAll': 'Ver todos',
    'recipientsLoadFailed': 'No se pudieron cargar los destinatarios.',
    'noRecipients': 'Aún no hay destinatarios',
    'addRecipientBeforeTransfer':
        'Agrega un destinatario antes de tu primera transferencia.',
    'add': 'Agregar',
    'haitiWallet': 'Billetera de Haití',
    'recentTransfers': 'Transferencias recientes',
    'seeHistory': 'Ver historial',
    'noTransfers': 'Aún no hay transferencias',
    'submittedTransfersHere': 'Tus transferencias enviadas aparecerán aquí.',
    'send': 'Enviar',
    'usdSubmitted': 'USD enviados',
    'inProgress': 'En curso',
    'newTransfer': 'Nueva transferencia',
    'historyUnavailable': 'El historial de transferencias no está disponible.',
    'historyEmptyBody':
        'Las transferencias completadas y pendientes aparecerán aquí.',
    'transferHistory': 'Historial de transferencias',
    'transferHistoryBody':
        'Toca una transferencia para ver el recibo y la referencia.',
    'addRecipient': 'Agregar destinatario',
    'peopleYouSupport': 'Personas que apoyas',
    'recipientsSubtitle':
        'Guarda contactos y datos de pago de Haití para transferir más rápido.',
    'searchNamePhone': 'Buscar nombre o teléfono',
    'noMatchingRecipients': 'Ningún destinatario coincide con tu búsqueda.',
    'edit': 'Editar',
    'delete': 'Eliminar',
    'deleteRecipient': '¿Eliminar destinatario?',
    'removeRecipient': '¿Eliminar a {name} de tus destinatarios guardados?',
    'recipientNotDeleted': 'No se eliminó el destinatario.',
    'editRecipient': 'Editar destinatario',
    'fullName': 'Nombre completo',
    'haitiPhone': 'Teléfono de Haití',
    'streetAddress': 'Dirección',
    'city': 'Ciudad',
    'department': 'Departamento',
    'deliveryWallet': 'Billetera de entrega',
    'saveRecipient': 'Guardar destinatario',
    'saveChanges': 'Guardar cambios',
    'recipientSaveFailed': 'No se pudo guardar el destinatario.',
    'helpSafety': 'Ayuda y seguridad',
    'sandboxNotice':
        'Esta versión funciona en modo de prueba. Registra transferencias de prueba, pero no cobra fondos ni envía pagos reales.',
    'protectAccount': 'Protege tu cuenta',
    'protectAccountBody':
        'Nunca compartas tu contraseña ni códigos. TiCash nunca te pedirá dinero para desbloquear una cuenta.',
    'transferAssistance': 'Ayuda con transferencias',
    'transferAssistanceBody':
        'Abre Transferencias, selecciona la transferencia y guarda su referencia.',
    'privacy': 'Privacidad',
    'privacyBody':
        'Los datos de cuenta y transferencias se guardan en la API configurada de TiCash.',
    'termsFees': 'Términos y tarifas',
    'termsFeesBody': 'Las tasas y tarifas mostradas son valores de prueba.',
    'testingHelp':
        'Para problemas de prueba, contacta al administrador y comparte solo la referencia, nunca tu contraseña.',
    'wallet': 'Billetera',
    'transferAccount': 'Cuenta de transferencias TiCash',
    'noStoredBalance': 'Sin saldo almacenado',
    'loadingActivity': 'Cargando actividad…',
    'transfersRecorded': '{count} transferencias registradas',
    'fundingStatus': 'Estado de fondos',
    'fundingNotConnected': 'Los fondos por tarjeta y banco no están conectados',
    'fundingProviderRequired':
        'Los fondos reales requieren un proveedor aprobado',
    'qrUnavailable': 'La recepción por QR no está disponible',
    'sandboxNoFunds': 'TiCash no guarda fondos de clientes en modo de prueba',
    'sendToHaiti': 'Enviar a Haití',
    'guest': 'Invitado',
    'identityReview': 'Revisión de identidad',
    'unknown': 'desconocido',
    'personalInformation': 'Información personal',
    'addMobile': 'Agrega tu número móvil',
    'identityVerification': 'Verificación de identidad',
    'requestManualReview': 'Solicitar una revisión manual segura',
    'changePassword': 'Cambiar contraseña',
    'changePasswordSubtitle': 'Actualiza tu contraseña de forma segura',
    'helpSubtitle': 'Estado de prueba, privacidad y ayuda',
    'adminDashboard': 'Abrir panel de administración',
    'logOut': 'Cerrar sesión',
    'currentPassword': 'Contraseña actual',
    'newPassword': 'Nueva contraseña',
    'confirmNewPassword': 'Confirmar nueva contraseña',
    'passwordsDoNotMatch': 'Las nuevas contraseñas no coinciden.',
    'passwordChanged': 'Contraseña cambiada. Inicia sesión de nuevo.',
    'editProfile': 'Editar perfil',
    'mobilePhone': 'Teléfono móvil',
    'includeCountryCode': 'Incluye el código de país',
    'profileUpdated': 'Perfil actualizado.',
    'requestIdentityReview': 'Solicitar revisión de identidad',
    'requestReview': 'Solicitar revisión',
    'identityReviewRequested': 'Revisión de identidad solicitada.',
    'transferReceipt': 'Recibo de transferencia',
    'status': 'Estado',
    'recipient': 'Destinatario',
    'delivery': 'Entrega',
    'youSend': 'Envías',
    'fee': 'Tarifa',
    'exchangeRate': 'Tipo de cambio',
    'recipientReceives': 'El destinatario recibe',
    'reference': 'Referencia',
    'created': 'Creado',
    'completed': 'COMPLETADA',
    'failed': 'FALLIDA',
    'cancelled': 'CANCELADA',
    'reversed': 'REVERTIDA',
    'processing': 'PROCESANDO',
    'pending': 'PENDIENTE',
    'amount': 'Monto',
    'deliveryStep': 'Entrega',
    'payment': 'Pago',
    'review': 'Revisar',
    'done': 'Listo',
    'amountError': 'Ingresa un monto entre 1 y 10.000 USD.',
    'recipientError': 'Completa los datos con un teléfono válido de Haití.',
    'quoteUnavailable':
        'El servicio de cotización no está disponible. No se envió ninguna transferencia.',
    'transferNotSubmitted':
        'La transferencia no se envió. Reintentar conservará la misma referencia.',
    'confirmSend': 'Confirmar y enviar',
    'howMuch': '¿Cuánto quieres enviar?',
    'amountSubtitle':
        'Ingresa USD. TiCash calcula las tarifas y el monto en HTG antes de revisar.',
    'whoReceiving': '¿Quién recibe?',
    'recipientLegal': 'Usa el nombre legal y los datos de contacto de Haití.',
    'haitiPhoneHelper': '+509 seguido de 8 dígitos',
    'chooseDelivery': 'Elegir entrega',
    'deliverySubtitle':
        'Selecciona la billetera asociada al teléfono del destinatario.',
    'mobileWalletDelivery': 'Entrega a billetera móvil',
    'availabilityTiming':
        'La disponibilidad depende de integraciones aprobadas.',
    'paymentSubtitle':
        'Revisa el estado de fondos antes de solicitar la cotización.',
    'testMode': 'Modo de prueba',
    'noCharge': 'No se cobrará ninguna tarjeta o cuenta bancaria.',
    'usdRequested': '{amount} USD solicitados',
    'reviewTransfer': 'Revisar transferencia',
    'reviewSubtitle':
        'Estos valores vienen de la API de TiCash. Confirma cada detalle.',
    'phone': 'Teléfono',
    'total': 'Total',
    'recipientGets': 'El destinatario recibe',
    'testRecordNotice':
        'Enviar crea un registro de prueba. No se mueve dinero real.',
    'transferSubmitted': 'Transferencia enviada',
    'transferSuccessBody':
        'Tu registro de transferencia de prueba se creó correctamente.',
    'youSent': 'Enviaste',
    'viewTransfers': 'Ver transferencias',
    'sendAnother': 'Enviar otra transferencia',
    'stepProgress': 'Paso {current} de {total} • {label}',
    'identityRequired': 'Se requiere revisión de identidad',
    'identityPending': 'Tu revisión de identidad está pendiente.',
    'openProfileReview':
        'Abre tu perfil para solicitar la revisión manual disponible.',
    'openProfile': 'Abrir perfil',
    'preparingSession': 'Preparando tu sesión segura',
    'walletGeneric': 'Billetera',
    'identityReviewExplanation':
        'TiCash pondrá tu cuenta en revisión manual. Los documentos deben enviarse mediante un proveedor seguro aprobado antes de habilitar transferencias reales.',
    'beforeVerification': 'Antes de comenzar',
    'governmentIdRequired': 'Ten listo un documento oficial válido.',
    'cameraRequired': 'Permite el acceso a la cámara cuando Didit lo solicite.',
    'goodLightingRequired': 'Usa un lugar privado y bien iluminado.',
    'diditDisclosure':
        'Didit proporciona la verificación de identidad. TiCash no guarda imágenes de documentos ni selfis de este proceso. El acceso se concede solo después de que el servidor de TiCash confirme el resultado.',
    'continueVerification': 'Continuar verificación',
    'startVerification': 'Iniciar verificación de identidad',
    'checkVerificationStatus': 'Consultar estado de verificación',
    'verifyYourIdentity': 'Verifica tu identidad',
    'verifyIdentityBody':
        'Se requiere una verificación segura antes de habilitar transferencias de dinero real.',
    'verificationStarted': 'Verificación iniciada',
    'verificationStartedBody':
        'Continúa el proceso seguro o consulta un resultado actualizado.',
    'verificationInReview': 'Verificación en revisión',
    'verificationInReviewBody':
        'Didit está revisando tu verificación. TiCash actualizará tu cuenta después de confirmar el resultado en el servidor.',
    'verificationApproved': 'Identidad verificada',
    'verificationApprovedBody':
        'El backend de TiCash aprobó tu verificación de identidad.',
    'verificationDeclined': 'Verificación no aprobada',
    'verificationDeclinedBody':
        'No se pudo aprobar la verificación. Puedes iniciar una nueva o contactar a soporte.',
    'verificationExpired': 'Verificación vencida',
    'verificationExpiredBody':
        'Esta sesión venció. Inicia una nueva sesión segura para continuar.',
    'openIdentityVerification':
        'Completa la verificación segura antes de iniciar una transferencia.',
    'verifyIdentity': 'Verificar identidad',
  },
  AppLanguage.french: {
    'language': 'Langue',
    'changeLanguage': 'Changer de langue',
    'chooseLanguage': 'Choisissez votre langue',
    'back': 'Retour',
    'close': 'Fermer',
    'home': 'Accueil',
    'recipients': 'Bénéficiaires',
    'transfers': 'Transferts',
    'profile': 'Profil',
    'retry': 'Réessayer',
    'tryAgain': 'Réessayer',
    'cancel': 'Annuler',
    'save': 'Enregistrer',
    'update': 'Mettre à jour',
    'continue': 'Continuer',
    'required': 'Obligatoire',
    'welcomeBack': 'Bon retour',
    'signInSubtitle':
        'Connectez-vous pour gérer les bénéficiaires et suivre vos transferts.',
    'emailAddress': 'Adresse e-mail',
    'enterValidEmail': 'Saisissez une adresse e-mail valide',
    'password': 'Mot de passe',
    'showPassword': 'Afficher le mot de passe',
    'hidePassword': 'Masquer le mot de passe',
    'passwordMin': 'Le mot de passe doit contenir au moins 8 caractères',
    'passwordRecoveryUnavailable':
        'La récupération du mot de passe n’est pas encore disponible.',
    'forgotPassword': 'Mot de passe oublié ?',
    'signIn': 'Se connecter',
    'newToTiCash': 'Nouveau sur TiCash ?',
    'createAccount': 'Créer un compte',
    'sessionSecure': 'Votre session est stockée en sécurité sur cet appareil',
    'startWithTiCash': 'Commencez avec TiCash',
    'registerSubtitle':
        'Créez votre compte. Une vérification d’identité est requise avant les transferts.',
    'firstName': 'Prénom',
    'lastName': 'Nom',
    'useAtLeast8': 'Utilisez au moins 8 caractères',
    'testBuildDisclosure':
        'En continuant, vous reconnaissez que les paiements réels ne sont pas activés dans cette version de test.',
    'hiName': 'Bonjour, {name}',
    'there': 'vous',
    'sendSupportHome': 'Soutenez vos proches',
    'quoteSubtitle':
        'Obtenez un taux USD vers HTG calculé par le serveur avant l’envoi.',
    'startTransfer': 'Démarrer un transfert',
    'transferSummaryUnavailable': 'Le résumé des transferts est indisponible.',
    'viewAll': 'Voir tout',
    'recipientsLoadFailed': 'Impossible de charger les bénéficiaires.',
    'noRecipients': 'Aucun bénéficiaire',
    'addRecipientBeforeTransfer':
        'Ajoutez un bénéficiaire avant votre premier transfert.',
    'add': 'Ajouter',
    'haitiWallet': 'Portefeuille haïtien',
    'recentTransfers': 'Transferts récents',
    'seeHistory': 'Voir l’historique',
    'noTransfers': 'Aucun transfert',
    'submittedTransfersHere': 'Vos transferts apparaîtront ici.',
    'send': 'Envoyer',
    'usdSubmitted': 'USD envoyés',
    'inProgress': 'En cours',
    'newTransfer': 'Nouveau transfert',
    'historyUnavailable': 'L’historique est indisponible.',
    'historyEmptyBody':
        'Les transferts terminés et en attente apparaîtront ici.',
    'transferHistory': 'Historique des transferts',
    'transferHistoryBody':
        'Touchez un transfert pour voir son reçu et sa référence.',
    'addRecipient': 'Ajouter un bénéficiaire',
    'peopleYouSupport': 'Vos bénéficiaires',
    'recipientsSubtitle':
        'Enregistrez les contacts et détails de paiement haïtiens.',
    'searchNamePhone': 'Rechercher un nom ou téléphone',
    'noMatchingRecipients': 'Aucun bénéficiaire ne correspond.',
    'edit': 'Modifier',
    'delete': 'Supprimer',
    'deleteRecipient': 'Supprimer le bénéficiaire ?',
    'removeRecipient': 'Supprimer {name} de vos bénéficiaires ?',
    'recipientNotDeleted': 'Le bénéficiaire n’a pas été supprimé.',
    'editRecipient': 'Modifier le bénéficiaire',
    'fullName': 'Nom complet',
    'haitiPhone': 'Téléphone en Haïti',
    'streetAddress': 'Adresse',
    'city': 'Ville',
    'department': 'Département',
    'deliveryWallet': 'Portefeuille de réception',
    'saveRecipient': 'Enregistrer le bénéficiaire',
    'saveChanges': 'Enregistrer les modifications',
    'recipientSaveFailed': 'Impossible d’enregistrer le bénéficiaire.',
    'helpSafety': 'Aide et sécurité',
    'sandboxNotice':
        'Cette version fonctionne en mode test et n’effectue aucun paiement réel.',
    'protectAccount': 'Protégez votre compte',
    'protectAccountBody':
        'Ne partagez jamais votre mot de passe ou vos codes. TiCash ne demandera jamais d’argent pour débloquer un compte.',
    'transferAssistance': 'Assistance transfert',
    'transferAssistanceBody':
        'Ouvrez Transferts, sélectionnez le transfert et conservez sa référence.',
    'privacy': 'Confidentialité',
    'privacyBody': 'Les données sont stockées par l’API TiCash configurée.',
    'termsFees': 'Conditions et frais',
    'termsFeesBody': 'Les taux et frais affichés sont des valeurs de test.',
    'testingHelp':
        'Pour un problème de test, contactez l’administrateur avec la référence uniquement.',
    'wallet': 'Portefeuille',
    'transferAccount': 'Compte de transfert TiCash',
    'noStoredBalance': 'Aucun solde stocké',
    'loadingActivity': 'Chargement de l’activité…',
    'transfersRecorded': '{count} transferts enregistrés',
    'fundingStatus': 'État du financement',
    'fundingNotConnected':
        'Le financement par carte et banque n’est pas connecté',
    'fundingProviderRequired':
        'Le financement réel nécessite un fournisseur approuvé',
    'qrUnavailable': 'La réception QR est indisponible',
    'sandboxNoFunds': 'TiCash ne conserve aucun fonds client en mode test',
    'sendToHaiti': 'Envoyer en Haïti',
    'guest': 'Invité',
    'identityReview': 'Vérification d’identité',
    'unknown': 'inconnu',
    'personalInformation': 'Informations personnelles',
    'addMobile': 'Ajoutez votre numéro mobile',
    'identityVerification': 'Vérification d’identité',
    'requestManualReview': 'Demander une vérification manuelle sécurisée',
    'changePassword': 'Changer le mot de passe',
    'changePasswordSubtitle': 'Modifiez votre mot de passe en sécurité',
    'helpSubtitle': 'Mode test, confidentialité et aide',
    'adminDashboard': 'Ouvrir le tableau de bord admin',
    'logOut': 'Se déconnecter',
    'currentPassword': 'Mot de passe actuel',
    'newPassword': 'Nouveau mot de passe',
    'confirmNewPassword': 'Confirmer le nouveau mot de passe',
    'passwordsDoNotMatch': 'Les nouveaux mots de passe ne correspondent pas.',
    'passwordChanged': 'Mot de passe modifié. Reconnectez-vous.',
    'editProfile': 'Modifier le profil',
    'mobilePhone': 'Téléphone mobile',
    'includeCountryCode': 'Incluez l’indicatif du pays',
    'profileUpdated': 'Profil mis à jour.',
    'requestIdentityReview': 'Demander une vérification d’identité',
    'requestReview': 'Demander la vérification',
    'identityReviewRequested': 'Vérification demandée.',
    'transferReceipt': 'Reçu du transfert',
    'status': 'Statut',
    'recipient': 'Bénéficiaire',
    'delivery': 'Réception',
    'youSend': 'Vous envoyez',
    'fee': 'Frais',
    'exchangeRate': 'Taux de change',
    'recipientReceives': 'Le bénéficiaire reçoit',
    'reference': 'Référence',
    'created': 'Créé',
    'completed': 'TERMINÉ',
    'failed': 'ÉCHOUÉ',
    'cancelled': 'ANNULÉ',
    'reversed': 'ANNULÉ',
    'processing': 'EN COURS',
    'pending': 'EN ATTENTE',
    'amount': 'Montant',
    'deliveryStep': 'Réception',
    'payment': 'Paiement',
    'review': 'Vérifier',
    'done': 'Terminé',
    'amountError': 'Saisissez un montant entre 1 et 10 000 USD.',
    'recipientError':
        'Complétez les informations avec un numéro haïtien valide.',
    'quoteUnavailable':
        'Le service de devis est indisponible. Aucun transfert n’a été envoyé.',
    'transferNotSubmitted':
        'Le transfert n’a pas été envoyé. La même référence sera conservée.',
    'confirmSend': 'Confirmer et envoyer',
    'howMuch': 'Combien envoyez-vous ?',
    'amountSubtitle':
        'Saisissez des USD. TiCash calcule les frais et le montant HTG.',
    'whoReceiving': 'Qui reçoit ?',
    'recipientLegal': 'Utilisez le nom légal et les coordonnées en Haïti.',
    'haitiPhoneHelper': '+509 suivi de 8 chiffres',
    'chooseDelivery': 'Choisir la réception',
    'deliverySubtitle':
        'Sélectionnez le portefeuille lié au numéro du bénéficiaire.',
    'mobileWalletDelivery': 'Réception sur portefeuille mobile',
    'availabilityTiming':
        'La disponibilité dépend des intégrations approuvées.',
    'paymentSubtitle': 'Vérifiez le financement avant de demander le devis.',
    'testMode': 'Mode test',
    'noCharge': 'Aucune carte ou compte bancaire ne sera débité.',
    'usdRequested': '{amount} USD demandés',
    'reviewTransfer': 'Vérifier le transfert',
    'reviewSubtitle':
        'Ces valeurs viennent de l’API TiCash. Vérifiez chaque détail.',
    'phone': 'Téléphone',
    'total': 'Total',
    'recipientGets': 'Le bénéficiaire reçoit',
    'testRecordNotice':
        'L’envoi crée un transfert de test. Aucun argent réel ne circule.',
    'transferSubmitted': 'Transfert envoyé',
    'transferSuccessBody': 'Votre transfert de test a été créé avec succès.',
    'youSent': 'Vous avez envoyé',
    'viewTransfers': 'Voir les transferts',
    'sendAnother': 'Envoyer un autre transfert',
    'stepProgress': 'Étape {current} sur {total} • {label}',
    'identityRequired': 'Vérification d’identité requise',
    'identityPending': 'Votre vérification d’identité est en attente.',
    'openProfileReview':
        'Ouvrez votre profil pour demander la vérification manuelle.',
    'openProfile': 'Ouvrir le profil',
    'preparingSession': 'Préparation de votre session sécurisée',
    'walletGeneric': 'Portefeuille',
    'identityReviewExplanation':
        'TiCash placera votre compte en vérification manuelle. Les documents doivent passer par un fournisseur sécurisé approuvé avant les transferts réels.',
    'beforeVerification': 'Avant de commencer',
    'governmentIdRequired': 'Préparez une pièce d’identité officielle valide.',
    'cameraRequired': 'Autorisez la caméra lorsque Didit le demande.',
    'goodLightingRequired':
        'Installez-vous dans un lieu privé et bien éclairé.',
    'diditDisclosure':
        'Didit fournit la vérification d’identité. TiCash ne stocke pas les images de documents ni les selfies de ce parcours. L’accès est accordé uniquement après confirmation par le serveur TiCash.',
    'continueVerification': 'Continuer la vérification',
    'startVerification': 'Démarrer la vérification d’identité',
    'checkVerificationStatus': 'Vérifier le statut',
    'verifyYourIdentity': 'Vérifiez votre identité',
    'verifyIdentityBody':
        'Une vérification sécurisée est requise avant d’activer les transferts d’argent réel.',
    'verificationStarted': 'Vérification commencée',
    'verificationStartedBody':
        'Continuez le parcours sécurisé ou vérifiez si le résultat a été mis à jour.',
    'verificationInReview': 'Vérification en cours d’examen',
    'verificationInReviewBody':
        'Didit examine votre vérification. TiCash mettra votre compte à jour après confirmation du serveur.',
    'verificationApproved': 'Identité vérifiée',
    'verificationApprovedBody':
        'Votre vérification d’identité a été approuvée par le serveur TiCash.',
    'verificationDeclined': 'Vérification non approuvée',
    'verificationDeclinedBody':
        'La vérification n’a pas pu être approuvée. Vous pouvez recommencer ou contacter l’assistance.',
    'verificationExpired': 'Vérification expirée',
    'verificationExpiredBody':
        'Cette session a expiré. Démarrez une nouvelle session sécurisée.',
    'openIdentityVerification':
        'Terminez la vérification sécurisée avant de démarrer un transfert.',
    'verifyIdentity': 'Vérifier mon identité',
  },
  AppLanguage.haitianCreole: {
    'language': 'Lang',
    'changeLanguage': 'Chanje lang',
    'chooseLanguage': 'Chwazi lang ou',
    'back': 'Retounen',
    'close': 'Fèmen',
    'home': 'Akèy',
    'recipients': 'Benefisyè',
    'transfers': 'Transfè',
    'profile': 'Pwofil',
    'retry': 'Eseye ankò',
    'tryAgain': 'Eseye ankò',
    'cancel': 'Anile',
    'save': 'Sove',
    'update': 'Mete ajou',
    'continue': 'Kontinye',
    'required': 'Obligatwa',
    'welcomeBack': 'Byenvini ankò',
    'signInSubtitle': 'Konekte pou jere benefisyè yo epi swiv transfè ou yo.',
    'emailAddress': 'Adrès imèl',
    'enterValidEmail': 'Antre yon adrès imèl ki valab',
    'password': 'Modpas',
    'showPassword': 'Montre modpas',
    'hidePassword': 'Kache modpas',
    'passwordMin': 'Modpas la dwe gen omwen 8 karaktè',
    'passwordRecoveryUnavailable': 'Rekipere modpas poko disponib.',
    'forgotPassword': 'Ou bliye modpas ou?',
    'signIn': 'Konekte',
    'newToTiCash': 'Ou nouvo sou TiCash?',
    'createAccount': 'Kreye kont',
    'sessionSecure': 'Sesyon ou sere an sekirite sou aparèy sa a',
    'startWithTiCash': 'Kòmanse ak TiCash',
    'registerSubtitle':
        'Kreye kont ou. Yo dwe verifye idantite ou anvan transfè.',
    'firstName': 'Prenon',
    'lastName': 'Siyati',
    'useAtLeast8': 'Itilize omwen 8 karaktè',
    'testBuildDisclosure':
        'Lè ou kontinye, ou rekonèt peman reyèl yo pa aktive nan vèsyon tès sa a.',
    'hiName': 'Bonjou, {name}',
    'there': 'zanmi',
    'sendSupportHome': 'Voye sipò lakay',
    'quoteSubtitle': 'Jwenn yon pri USD pou HTG sèvè a kalkile anvan ou voye.',
    'startTransfer': 'Kòmanse yon transfè',
    'transferSummaryUnavailable': 'Rezime transfè yo pa disponib.',
    'viewAll': 'Wè tout',
    'recipientsLoadFailed': 'Benefisyè yo pa t ka chaje.',
    'noRecipients': 'Pa gen benefisyè ankò',
    'addRecipientBeforeTransfer':
        'Ajoute yon benefisyè anvan premye transfè ou.',
    'add': 'Ajoute',
    'haitiWallet': 'Bous Ayiti',
    'recentTransfers': 'Dènye transfè yo',
    'seeHistory': 'Wè istorik',
    'noTransfers': 'Pa gen transfè ankò',
    'submittedTransfersHere': 'Transfè ou voye yo ap parèt la.',
    'send': 'Voye',
    'usdSubmitted': 'USD voye',
    'inProgress': 'An pwogrè',
    'newTransfer': 'Nouvo transfè',
    'historyUnavailable': 'Istorik transfè yo pa disponib.',
    'historyEmptyBody': 'Transfè ki fini ak sa k ap tann yo ap parèt la.',
    'transferHistory': 'Istorik transfè',
    'transferHistoryBody': 'Peze yon transfè pou wè resi ak referans li.',
    'addRecipient': 'Ajoute benefisyè',
    'peopleYouSupport': 'Moun ou sipòte',
    'recipientsSubtitle':
        'Sove kontak ak detay peman Ayiti pou transfè pi rapid.',
    'searchNamePhone': 'Chèche non oswa telefòn',
    'noMatchingRecipients': 'Pa gen benefisyè ki koresponn.',
    'edit': 'Modifye',
    'delete': 'Efase',
    'deleteRecipient': 'Efase benefisyè a?',
    'removeRecipient': 'Retire {name} nan benefisyè ou yo?',
    'recipientNotDeleted': 'Benefisyè a pa t efase.',
    'editRecipient': 'Modifye benefisyè',
    'fullName': 'Non konplè',
    'haitiPhone': 'Nimewo telefòn Ayiti',
    'streetAddress': 'Adrès',
    'city': 'Vil',
    'department': 'Depatman',
    'deliveryWallet': 'Bous resepsyon',
    'saveRecipient': 'Sove benefisyè',
    'saveChanges': 'Sove chanjman',
    'recipientSaveFailed': 'Benefisyè a pa t ka sove.',
    'helpSafety': 'Èd ak sekirite',
    'sandboxNotice':
        'Vèsyon sa a nan mòd tès. Li pa pran lajan ni voye peman reyèl.',
    'protectAccount': 'Pwoteje kont ou',
    'protectAccountBody':
        'Pa janm pataje modpas oswa kòd ou. TiCash pap mande w lajan pou debloke kont ou.',
    'transferAssistance': 'Èd pou transfè',
    'transferAssistanceBody':
        'Louvri Transfè, chwazi transfè a epi kenbe referans li.',
    'privacy': 'Konfidansyalite',
    'privacyBody': 'API TiCash la sere done kont ak transfè yo.',
    'termsFees': 'Kondisyon ak frè',
    'termsFeesBody': 'To ak frè ki parèt yo se valè tès.',
    'testingHelp':
        'Pou pwoblèm tès, kontakte administratè a ak referans lan sèlman.',
    'wallet': 'Bous',
    'transferAccount': 'Kont transfè TiCash',
    'noStoredBalance': 'Pa gen balans sere',
    'loadingActivity': 'Aktivite ap chaje…',
    'transfersRecorded': '{count} transfè anrejistre',
    'fundingStatus': 'Eta finansman',
    'fundingNotConnected': 'Kat ak bank poko konekte',
    'fundingProviderRequired': 'Finansman reyèl bezwen yon founisè apwouve',
    'qrUnavailable': 'Resevwa ak QR pa disponib',
    'sandboxNoFunds': 'TiCash pa kenbe lajan kliyan nan mòd tès',
    'sendToHaiti': 'Voye Ayiti',
    'guest': 'Envite',
    'identityReview': 'Verifikasyon idantite',
    'unknown': 'enkoni',
    'personalInformation': 'Enfòmasyon pèsonèl',
    'addMobile': 'Ajoute nimewo mobil ou',
    'identityVerification': 'Verifikasyon idantite',
    'requestManualReview': 'Mande yon verifikasyon manyèl an sekirite',
    'changePassword': 'Chanje modpas',
    'changePasswordSubtitle': 'Mete modpas ou ajou an sekirite',
    'helpSubtitle': 'Mòd tès, konfidansyalite ak èd',
    'adminDashboard': 'Louvri panèl admin',
    'logOut': 'Dekonekte',
    'currentPassword': 'Modpas aktyèl',
    'newPassword': 'Nouvo modpas',
    'confirmNewPassword': 'Konfime nouvo modpas',
    'passwordsDoNotMatch': 'Nouvo modpas yo pa menm.',
    'passwordChanged': 'Modpas chanje. Konekte ankò.',
    'editProfile': 'Modifye pwofil',
    'mobilePhone': 'Telefòn mobil',
    'includeCountryCode': 'Mete kòd peyi a',
    'profileUpdated': 'Pwofil mete ajou.',
    'requestIdentityReview': 'Mande verifikasyon idantite',
    'requestReview': 'Mande verifikasyon',
    'identityReviewRequested': 'Verifikasyon mande.',
    'transferReceipt': 'Resi transfè',
    'status': 'Eta',
    'recipient': 'Benefisyè',
    'delivery': 'Resepsyon',
    'youSend': 'Ou voye',
    'fee': 'Frè',
    'exchangeRate': 'To chanj',
    'recipientReceives': 'Benefisyè a resevwa',
    'reference': 'Referans',
    'created': 'Kreye',
    'completed': 'FINI',
    'failed': 'ECHWE',
    'cancelled': 'ANILE',
    'reversed': 'RANVÈSE',
    'processing': 'AP TRETE',
    'pending': 'AP TANN',
    'amount': 'Kantite',
    'deliveryStep': 'Resepsyon',
    'payment': 'Peman',
    'review': 'Verifye',
    'done': 'Fini',
    'amountError': 'Antre yon kantite ant 1 ak 10,000 USD.',
    'recipientError':
        'Ranpli tout detay yo ak yon nimewo telefòn Ayiti ki valab.',
    'quoteUnavailable': 'Sèvis pri a pa disponib. Pa gen transfè ki voye.',
    'transferNotSubmitted':
        'Transfè a pa t voye. Eseye ankò ap kenbe menm referans lan.',
    'confirmSend': 'Konfime epi voye',
    'howMuch': 'Konbyen ou ap voye?',
    'amountSubtitle':
        'Antre USD. TiCash kalkile frè ak kantite HTG anvan verifikasyon.',
    'whoReceiving': 'Kilès k ap resevwa?',
    'recipientLegal': 'Itilize non legal ak kontak Ayiti benefisyè a.',
    'haitiPhoneHelper': '+509 epi 8 chif',
    'chooseDelivery': 'Chwazi resepsyon',
    'deliverySubtitle': 'Chwazi bous ki asosye ak telefòn benefisyè a.',
    'mobileWalletDelivery': 'Resevwa nan bous mobil',
    'availabilityTiming': 'Disponibilite depann de entegrasyon ki apwouve.',
    'paymentSubtitle': 'Verifye finansman anvan ou mande pri a.',
    'testMode': 'Mòd tès',
    'noCharge': 'Yo pap chaje okenn kat oswa kont labank.',
    'usdRequested': '{amount} USD mande',
    'reviewTransfer': 'Verifye transfè',
    'reviewSubtitle': 'Valè sa yo soti nan API TiCash. Verifye tout detay.',
    'phone': 'Telefòn',
    'total': 'Total',
    'recipientGets': 'Benefisyè a resevwa',
    'testRecordNotice':
        'Voye a kreye yon transfè tès. Pa gen lajan reyèl ki deplase.',
    'transferSubmitted': 'Transfè voye',
    'transferSuccessBody': 'Transfè tès ou a kreye avèk siksè.',
    'youSent': 'Ou voye',
    'viewTransfers': 'Wè transfè yo',
    'sendAnother': 'Voye yon lòt transfè',
    'stepProgress': 'Etap {current} sou {total} • {label}',
    'identityRequired': 'Verifikasyon idantite obligatwa',
    'identityPending': 'Verifikasyon idantite ou ap tann.',
    'openProfileReview': 'Louvri pwofil ou pou mande verifikasyon manyèl la.',
    'openProfile': 'Louvri pwofil',
    'preparingSession': 'N ap prepare sesyon an sekirite ou',
    'walletGeneric': 'Bous',
    'identityReviewExplanation':
        'TiCash ap mete kont ou nan verifikasyon manyèl. Dokiman idantite yo dwe pase nan yon founisè sekirize ki apwouve anvan transfè reyèl aktive.',
    'beforeVerification': 'Anvan ou kòmanse',
    'governmentIdRequired': 'Prepare yon pyès idantite ofisyèl ki valab.',
    'cameraRequired': 'Bay kamera aksè lè Didit mande li.',
    'goodLightingRequired': 'Chwazi yon kote prive ki gen bon limyè.',
    'diditDisclosure':
        'Didit bay sèvis verifikasyon idantite a. TiCash pa sere foto dokiman oswa selfie ki soti nan pwosesis sa a. Aksè ap louvri sèlman apre sèvè TiCash la konfime rezilta a.',
    'continueVerification': 'Kontinye verifikasyon',
    'startVerification': 'Kòmanse verifikasyon idantite',
    'checkVerificationStatus': 'Tcheke eta verifikasyon an',
    'verifyYourIdentity': 'Verifye idantite ou',
    'verifyIdentityBody':
        'Yon verifikasyon sekirize obligatwa anvan transfè lajan reyèl ka aktive.',
    'verificationStarted': 'Verifikasyon kòmanse',
    'verificationStartedBody':
        'Kontinye pwosesis sekirize a oswa tcheke si gen yon nouvo rezilta.',
    'verificationInReview': 'Verifikasyon an ap revize',
    'verificationInReviewBody':
        'Didit ap revize verifikasyon ou. TiCash ap mete kont ou ajou apre sèvè a konfime rezilta a.',
    'verificationApproved': 'Idantite verifye',
    'verificationApprovedBody':
        'Sèvè TiCash la apwouve verifikasyon idantite ou.',
    'verificationDeclined': 'Verifikasyon pa apwouve',
    'verificationDeclinedBody':
        'Verifikasyon an pa t ka apwouve. Ou ka kòmanse ankò oswa kontakte sipò.',
    'verificationExpired': 'Verifikasyon ekspire',
    'verificationExpiredBody':
        'Sesyon sa a ekspire. Kòmanse yon nouvo sesyon sekirize.',
    'openIdentityVerification':
        'Fini verifikasyon sekirize a anvan ou kòmanse yon transfè.',
    'verifyIdentity': 'Verifye idantite',
  },
  AppLanguage.portuguese: {
    'language': 'Idioma',
    'changeLanguage': 'Alterar idioma',
    'chooseLanguage': 'Escolha seu idioma',
    'back': 'Voltar',
    'close': 'Fechar',
    'home': 'Início',
    'recipients': 'Destinatários',
    'transfers': 'Transferências',
    'profile': 'Perfil',
    'retry': 'Tentar novamente',
    'tryAgain': 'Tentar novamente',
    'cancel': 'Cancelar',
    'save': 'Salvar',
    'update': 'Atualizar',
    'continue': 'Continuar',
    'required': 'Obrigatório',
    'welcomeBack': 'Bem-vindo de volta',
    'signInSubtitle':
        'Entre para gerenciar destinatários e acompanhar suas transferências.',
    'emailAddress': 'Endereço de e-mail',
    'enterValidEmail': 'Digite um e-mail válido',
    'password': 'Senha',
    'showPassword': 'Mostrar senha',
    'hidePassword': 'Ocultar senha',
    'passwordMin': 'A senha deve ter pelo menos 8 caracteres',
    'passwordRecoveryUnavailable':
        'A recuperação de senha ainda não está disponível.',
    'forgotPassword': 'Esqueceu a senha?',
    'signIn': 'Entrar',
    'newToTiCash': 'Novo no TiCash?',
    'createAccount': 'Criar conta',
    'sessionSecure': 'Sua sessão é armazenada com segurança neste dispositivo',
    'startWithTiCash': 'Comece com TiCash',
    'registerSubtitle':
        'Crie sua conta. A verificação de identidade é necessária antes das transferências.',
    'firstName': 'Nome',
    'lastName': 'Sobrenome',
    'useAtLeast8': 'Use pelo menos 8 caracteres',
    'testBuildDisclosure':
        'Ao continuar, você reconhece que pagamentos reais não estão ativados nesta versão de teste.',
    'hiName': 'Olá, {name}',
    'there': 'amigo',
    'sendSupportHome': 'Envie apoio para casa',
    'quoteSubtitle':
        'Obtenha uma cotação de USD para HTG calculada pelo servidor antes de enviar.',
    'startTransfer': 'Iniciar transferência',
    'transferSummaryUnavailable':
        'O resumo de transferências não está disponível.',
    'viewAll': 'Ver todos',
    'recipientsLoadFailed': 'Não foi possível carregar os destinatários.',
    'noRecipients': 'Ainda não há destinatários',
    'addRecipientBeforeTransfer':
        'Adicione um destinatário antes da primeira transferência.',
    'add': 'Adicionar',
    'haitiWallet': 'Carteira do Haiti',
    'recentTransfers': 'Transferências recentes',
    'seeHistory': 'Ver histórico',
    'noTransfers': 'Ainda não há transferências',
    'submittedTransfersHere': 'Suas transferências aparecerão aqui.',
    'send': 'Enviar',
    'usdSubmitted': 'USD enviados',
    'inProgress': 'Em andamento',
    'newTransfer': 'Nova transferência',
    'historyUnavailable': 'O histórico de transferências não está disponível.',
    'historyEmptyBody':
        'Transferências concluídas e pendentes aparecerão aqui.',
    'transferHistory': 'Histórico de transferências',
    'transferHistoryBody':
        'Toque em uma transferência para ver o recibo e a referência.',
    'addRecipient': 'Adicionar destinatário',
    'peopleYouSupport': 'Pessoas que você apoia',
    'recipientsSubtitle':
        'Salve contatos e detalhes de pagamento do Haiti para transferências mais rápidas.',
    'searchNamePhone': 'Buscar nome ou telefone',
    'noMatchingRecipients': 'Nenhum destinatário encontrado.',
    'edit': 'Editar',
    'delete': 'Excluir',
    'deleteRecipient': 'Excluir destinatário?',
    'removeRecipient': 'Remover {name} dos destinatários salvos?',
    'recipientNotDeleted': 'O destinatário não foi excluído.',
    'editRecipient': 'Editar destinatário',
    'fullName': 'Nome completo',
    'haitiPhone': 'Telefone do Haiti',
    'streetAddress': 'Endereço',
    'city': 'Cidade',
    'department': 'Departamento',
    'deliveryWallet': 'Carteira de recebimento',
    'saveRecipient': 'Salvar destinatário',
    'saveChanges': 'Salvar alterações',
    'recipientSaveFailed': 'Não foi possível salvar o destinatário.',
    'helpSafety': 'Ajuda e segurança',
    'sandboxNotice':
        'Esta versão funciona em modo de teste e não processa pagamentos reais.',
    'protectAccount': 'Proteja sua conta',
    'protectAccountBody':
        'Nunca compartilhe sua senha ou códigos. O TiCash nunca pedirá dinheiro para desbloquear uma conta.',
    'transferAssistance': 'Ajuda com transferências',
    'transferAssistanceBody':
        'Abra Transferências, selecione a transferência e guarde a referência.',
    'privacy': 'Privacidade',
    'privacyBody': 'Os dados são armazenados pela API TiCash configurada.',
    'termsFees': 'Termos e taxas',
    'termsFeesBody': 'As taxas e tarifas exibidas são valores de teste.',
    'testingHelp':
        'Para problemas de teste, contate o administrador apenas com a referência.',
    'wallet': 'Carteira',
    'transferAccount': 'Conta de transferência TiCash',
    'noStoredBalance': 'Sem saldo armazenado',
    'loadingActivity': 'Carregando atividade…',
    'transfersRecorded': '{count} transferências registradas',
    'fundingStatus': 'Status de financiamento',
    'fundingNotConnected': 'Cartão e banco não estão conectados',
    'fundingProviderRequired':
        'O financiamento real exige um provedor aprovado',
    'qrUnavailable': 'O recebimento por QR não está disponível',
    'sandboxNoFunds': 'O TiCash não guarda fundos de clientes no modo de teste',
    'sendToHaiti': 'Enviar para o Haiti',
    'guest': 'Convidado',
    'identityReview': 'Verificação de identidade',
    'unknown': 'desconhecido',
    'personalInformation': 'Informações pessoais',
    'addMobile': 'Adicione seu número de celular',
    'identityVerification': 'Verificação de identidade',
    'requestManualReview': 'Solicitar uma revisão manual segura',
    'changePassword': 'Alterar senha',
    'changePasswordSubtitle': 'Atualize sua senha com segurança',
    'helpSubtitle': 'Modo de teste, privacidade e ajuda',
    'adminDashboard': 'Abrir painel administrativo',
    'logOut': 'Sair',
    'currentPassword': 'Senha atual',
    'newPassword': 'Nova senha',
    'confirmNewPassword': 'Confirmar nova senha',
    'passwordsDoNotMatch': 'As novas senhas não coincidem.',
    'passwordChanged': 'Senha alterada. Entre novamente.',
    'editProfile': 'Editar perfil',
    'mobilePhone': 'Celular',
    'includeCountryCode': 'Inclua o código do país',
    'profileUpdated': 'Perfil atualizado.',
    'requestIdentityReview': 'Solicitar verificação de identidade',
    'requestReview': 'Solicitar revisão',
    'identityReviewRequested': 'Verificação solicitada.',
    'transferReceipt': 'Recibo da transferência',
    'status': 'Status',
    'recipient': 'Destinatário',
    'delivery': 'Entrega',
    'youSend': 'Você envia',
    'fee': 'Taxa',
    'exchangeRate': 'Taxa de câmbio',
    'recipientReceives': 'O destinatário recebe',
    'reference': 'Referência',
    'created': 'Criado',
    'completed': 'CONCLUÍDA',
    'failed': 'FALHOU',
    'cancelled': 'CANCELADA',
    'reversed': 'REVERTIDA',
    'processing': 'PROCESSANDO',
    'pending': 'PENDENTE',
    'amount': 'Valor',
    'deliveryStep': 'Entrega',
    'payment': 'Pagamento',
    'review': 'Revisar',
    'done': 'Concluído',
    'amountError': 'Digite um valor entre 1 e 10.000 USD.',
    'recipientError': 'Preencha os dados com um telefone válido do Haiti.',
    'quoteUnavailable':
        'O serviço de cotação está indisponível. Nenhuma transferência foi enviada.',
    'transferNotSubmitted':
        'A transferência não foi enviada. A mesma referência será mantida.',
    'confirmSend': 'Confirmar e enviar',
    'howMuch': 'Quanto você está enviando?',
    'amountSubtitle':
        'Digite USD. O TiCash calcula taxas e o valor em HTG antes da revisão.',
    'whoReceiving': 'Quem vai receber?',
    'recipientLegal': 'Use o nome legal e os dados de contato do Haiti.',
    'haitiPhoneHelper': '+509 seguido de 8 dígitos',
    'chooseDelivery': 'Escolher entrega',
    'deliverySubtitle':
        'Selecione a carteira associada ao telefone do destinatário.',
    'mobileWalletDelivery': 'Entrega em carteira móvel',
    'availabilityTiming': 'A disponibilidade depende de integrações aprovadas.',
    'paymentSubtitle': 'Revise o financiamento antes de solicitar a cotação.',
    'testMode': 'Modo de teste',
    'noCharge': 'Nenhum cartão ou conta bancária será cobrado.',
    'usdRequested': '{amount} USD solicitados',
    'reviewTransfer': 'Revisar transferência',
    'reviewSubtitle':
        'Estes valores vieram da API TiCash. Confirme todos os detalhes.',
    'phone': 'Telefone',
    'total': 'Total',
    'recipientGets': 'O destinatário recebe',
    'testRecordNotice':
        'O envio cria um registro de teste. Nenhum dinheiro real é movimentado.',
    'transferSubmitted': 'Transferência enviada',
    'transferSuccessBody': 'Seu registro de transferência de teste foi criado.',
    'youSent': 'Você enviou',
    'viewTransfers': 'Ver transferências',
    'sendAnother': 'Enviar outra transferência',
    'stepProgress': 'Etapa {current} de {total} • {label}',
    'identityRequired': 'Verificação de identidade necessária',
    'identityPending': 'Sua verificação de identidade está pendente.',
    'openProfileReview': 'Abra seu perfil para solicitar a revisão manual.',
    'openProfile': 'Abrir perfil',
    'preparingSession': 'Preparando sua sessão segura',
    'walletGeneric': 'Carteira',
    'identityReviewExplanation':
        'O TiCash colocará sua conta em revisão manual. Os documentos devem passar por um provedor seguro aprovado antes das transferências reais.',
    'beforeVerification': 'Antes de começar',
    'governmentIdRequired': 'Tenha um documento oficial válido em mãos.',
    'cameraRequired': 'Permita o acesso à câmera quando o Didit solicitar.',
    'goodLightingRequired': 'Use um local privado e bem iluminado.',
    'diditDisclosure':
        'A verificação de identidade é fornecida pelo Didit. O TiCash não armazena imagens de documentos nem selfies deste fluxo. O acesso só é liberado depois que o servidor TiCash confirma o resultado.',
    'continueVerification': 'Continuar verificação',
    'startVerification': 'Iniciar verificação de identidade',
    'checkVerificationStatus': 'Verificar status',
    'verifyYourIdentity': 'Verifique sua identidade',
    'verifyIdentityBody':
        'A verificação segura é necessária antes de ativar transferências de dinheiro real.',
    'verificationStarted': 'Verificação iniciada',
    'verificationStartedBody':
        'Continue o fluxo seguro ou verifique se há um resultado atualizado.',
    'verificationInReview': 'Verificação em análise',
    'verificationInReviewBody':
        'O Didit está analisando sua verificação. O TiCash atualizará sua conta após a confirmação do servidor.',
    'verificationApproved': 'Identidade verificada',
    'verificationApprovedBody':
        'Sua verificação de identidade foi aprovada pelo backend do TiCash.',
    'verificationDeclined': 'Verificação não aprovada',
    'verificationDeclinedBody':
        'Não foi possível aprovar a verificação. Você pode iniciar uma nova ou contatar o suporte.',
    'verificationExpired': 'Verificação expirada',
    'verificationExpiredBody':
        'Esta sessão expirou. Inicie uma nova sessão segura para continuar.',
    'openIdentityVerification':
        'Conclua a verificação segura antes de iniciar uma transferência.',
    'verifyIdentity': 'Verificar identidade',
  },
};
